'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process');const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'..'),out=process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results/rc132');fs.mkdirSync(out,{recursive:true});
const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.webp':'image/webp','.png':'image/png','.wav':'audio/wav','.mp3':'audio/mpeg','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={status:'diagnostic_only',commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),scope:'explicit boss-checkpoint fixture, not natural campaign clear',errors:[],httpErrors:[],samples:[]};
try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1180,height:757}});page.on('pageerror',e=>report.errors.push(String(e.stack||e)));page.on('response',r=>{if(r.status()>=400)report.httpErrors.push({url:r.url(),status:r.status()});});
await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_SAMONG_RC91__?.installed);await page.keyboard.press('Escape');await page.evaluate(()=>window.__HAPIL_SAMONG_RC91__.unlock(null,'777'));await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();await page.locator('[data-game-mode-v31354="DREAM"]').click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__);for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
report.apis=await page.evaluate(()=>({qa:Object.keys(window.__MONGSE_QA_API__||{}),native:Object.keys(window.__HAPIL_RC95_NATIVE__||{}),controls:Object.keys(window.__HAPIL_CONTROLS_V31329__?.binding||{}),core:Object.keys(window.__HAPIL_COMBAT_CORE_V31401__||{}),rpg:Object.keys(window.__HAPIL_DANMAKU_RPG_RC88__||{}),modes:Object.keys(window.__HAPIL_MODES_V31346__||{})}));
report.stage=await page.evaluate(()=>{const result=window.__MONGSE_QA_API__.stageV3128BossShowcase('ep1b07');const s=window.__MONGSE_QA_STATE__;s.activeHeroId='hunter';s.invulnerableUntil=s.time;window.__HAPIL_CONTROLS_V31329__.setMode('full');return result;});
for(let i=0;i<35;i++){await page.waitForTimeout(2000);const row=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;const flags=Object.fromEntries(Object.entries(s).filter(([k,v])=>/clear|complete|defeat|lock|pause|wave|growth|frontier|progress/i.test(k)&&['number','string','boolean'].includes(typeof v)));return{zone:s.zone,time:s.time,hp:s.hp,x:s.x,y:s.y,flags,bossDefeated:s.bossDefeated,waves:[...s.spawnedWaves],clues:[...s.clues],drops:s.egoDrops?.length,enemies:(s.enemies||[]).map(a=>({id:a.id,hp:a.hp,maxHp:a.maxHp,phase:a.currentPhase,phaseTransitionActive:a.phaseTransitionActive,phaseTransitionUntil:a.phaseTransitionUntil,revival:a.revivalPending,friendly:a.friendly,required:a.requiredForClear,visualOnly:a.visualOnly})),flow:window.__HAPIL_FLOW_V31343__?.gate(s),auto:s.autoProgressV31301,mirror:window.__HAPIL_MIRROR_V31347__?.metrics(),budget:window.__HAPIL_DREAM_BALANCE_RC132__?.snapshot(),story:!!document.querySelector('#hapil-story-rc51'),ui:document.body.innerText.slice(-1800)};});report.samples.push(row);fs.writeFileSync(path.join(out,'wrath-probe.json'),JSON.stringify(report,null,2));if(row.zone!=='ep1b07'||row.hp<=0)break;}
await page.screenshot({path:path.join(out,'wrath-probe.png')});console.log('RC132_DIAGNOSTIC',JSON.stringify({errors:report.errors,api:report.apis,last:report.samples.at(-1)}));
}catch(e){report.status='failed';report.error=String(e.stack||e);process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'wrath-probe.json'),JSON.stringify(report,null,2));await browser?.close();server.close();}})();
