'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');let clock=0,checks=0;const check=(v,m)=>{checks++;assert(v,m);};
const window={performance:{now:()=>clock*1000},innerWidth:1280,innerHeight:720},c={window,console,WeakMap,Map,Set,Object,Math,Number,module:{exports:{}},setTimeout(){}};vm.createContext(c);
for(const f of ['assets/rc130/visual-policy.js','assets/rc130/audio-focus.js','assets/rc127/combat-policy.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});
const V=window.__HAPIL_VISUAL_RC130__,A=window.__HAPIL_AUDIO_RC130__,P=window.__HAPIL_POLICY_RC127__;
for(const [w,h]of[[40,40],[10000,5],[5,10000],[10000,10000],[0,0],[NaN,Infinity]])for(const dpr of[1,2,3])for(let angle=0;angle<Math.PI*2;angle+=Math.PI/8){const m={a:Math.cos(angle)*dpr,b:Math.sin(angle)*dpr,c:-Math.sin(angle)*dpr,d:Math.cos(angle)*dpr},f=V.fit(w,h,m,{width:390*dpr,height:422*dpr});check(f.projectedWidth<=78*dpr+1e-7&&f.projectedHeight<=84.4*dpr+1e-7,'20% limit after rotation and DPR');check(f.scale<=1&&f.scale>=0,'never enlarge');}
const p={danmakuV31316:true,x:16,y:16,radius:20},records=[],ctx={canvas:{width:1000,height:600},getTransform:()=>({a:1,b:0,c:0,d:1}),drawImage(...a){records.push(a);}};const old=ctx.drawImage;
V.drawProjectile((ctx)=>ctx.drawImage({},-500,-500,1000,1000),ctx,{},p,10,{});check(ctx.drawImage===old,'restore context method');check(records[0][3]===120&&records[0][4]===120,'uniform square cap');check(V.contactRadius({},p,200)<=60,'collision shrinks with capped sprite');
check(V.contactReady({},p,200),'rendered volume permitted');check(!V.contactReady({}, {danmakuV31316:true},200),'oversized unpainted volume is harmless');
for(const q of[{...p,friendly:true},{...p,heroId:'hwando'},{...p,laserV31330:true},{...p,shape:'line'}, {shape:'circle',radius:20}])check(!V.barrage(q),'exclude friendly skills and lasers');
const melee={enemyMeleeTelegraphV31237:true,normalMonsterEffect:true,x:2,y:3,born:10,life:.3};let a=V.stationary(melee,10.1);melee.x=99;melee.y=99;a=V.stationary(melee,10.2);check(a.effect.x===2&&a.effect.y===3&&a.effect.vx===0,'melee stays at initial attack point');check(a.alpha<1&&a.alpha>0,'melee fades');check(V.stationary(melee,10.31).expired,'melee expires');let capture=0;check(V.capture(()=>{capture++;return true;},melee)===false&&capture===0,'melee never enters exit flight');
for(const e of[{...melee,boss:true},{...melee,midboss:true},{...melee,normalRangedV31237:true},{...melee,bloodiedThrownRC43:true},{...melee,heroId:'hwando'}])check(!V.melee(e),'preserve thrown bosses, ranged and allied skills');
let liveInstalled=false,forwarded=0;window.__HAPIL_FEEDBACK_RC22__=Object.freeze({sounds:{}});window.__HAPIL_FEEDBACK_RC128__=Object.freeze({get installed(){return liveInstalled;},record(){forwarded++;return'original';}});check(A.install(),'audio adapters install');liveInstalled=true;check(window.__HAPIL_FEEDBACK_RC128__.installed,'preserve live getter');
let s={time:10,zone:'unit',activeHeroId:'seoha',hp:100},source={heroId:'seoha'};for(let i=0;i<12;i++)A.enemyHit(s,{},1,source);
const row={epoch:1,sequence:1,targetId:'__host',heroId:'seoha',kind:'CONTACT',result:'HIT',hpLoss:10,appliedDamage:10};check(window.__HAPIL_FEEDBACK_RC128__.record(s,s,row,{})==='original'&&forwarded===1,'forward native visual feedback');A.contact(s,s,row,{});let calls=[];A.tick(s,{sound:true,sfxVolume:1},(...x)=>calls.push(x),true);check(calls.length===1&&calls[0][0]===A.snapshot(s).neutralHurt,'hurt wins over enemy-hit queue');check(A.snapshot(s).history[0].gender==='female'&&!A.snapshot(s).history[0].vocal,'female identity with safe non-vocal fallback');check(A.snapshot().stats.duplicateEvents===1,'deduplicate contact');
clock=.1;s.time+=.1;A.contact(s,s,{...row,sequence:2},{});A.tick(s,{sound:true,sfxVolume:1},(...x)=>calls.push(x),true);check(calls.length===1,'hurt cooldown');
clock=2;s.time=12;for(let i=0;i<18;i++)A.enemyHit(s,{},1,source);A.tick(s,{sound:true,sfxVolume:1},(...x)=>calls.push(x),true);check(calls.length===2&&A.snapshot().stats.enemyHitPlayed===1,'occasional enemy hit');
clock=4;s.time=14;A.contact(s,s,{...row,sequence:3},{});A.tick(s,{sound:false,sfxVolume:1},()=>{throw Error('muted playback');},true);check(A.snapshot(s).queue===0,'muted queues do not replay later');
for(const h of['hwando','seoha','neon','michaela','lauren','hunter','slayer','gunner'])check(A.identity({...s,activeHeroId:h},s,{heroId:h}).voice===null,'do not invent gendered vocal assets');
check(A.permitNative('./audio/rc22/wood-hit-1.wav'),'native allied attack passes');check(A.permitNative('./audio/v3127/sfx-magic-spell-incantation-1.mp3'),'do not repurpose enemy voice');
for(const mode of['STORY','DREAM'])for(const count of[0,3,100,1e6]){const state={gameModeV31346:mode};const speed=P.speed(state,{speed:count},{mastery:count,awakened:true,awakeningMultiplier:9,accelerated:true,accelerationMultiplier:99});check(Math.abs(speed-4.75*1.21*1.126)<1e-8,'max777 reference independent of growth and buffs');}
const report={status:'passed',checks,scope:'unit/stub assertions, not natural gameplay or listening validation',audio:A.snapshot(s)};const out=path.join(process.env.HAPIL_QA_OUTPUT||'qa-results','rc130-policy');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log('RC130_POLICY_RESULT',JSON.stringify(report));
