'use strict';
// Native staged fixtures. Every forced health/time/progress change is deliberate test setup.
// These are browser emulations; no full natural campaign or physical phone claim.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'..'),out=path.join(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results'),'rc133');fs.mkdirSync(out,{recursive:true});
const bridge=`\nconst rc133Frame=$n;$n=function(...args){if(window.__RC133_FIXED_STATE__){args[1]=window.__RC133_FIXED_STATE__;args[3]=F.find(h=>h.id===args[1].activeHeroId)||args[3];}return rc133Frame(...args);};window.__RC133_QA__={initial:oi,get midbossTemplates(){return Object.entries(N).flatMap(([zone,z])=>(z.enemies??[]).filter(a=>a.midboss).map(a=>({zone,id:a.id})));},spawnMidbossWave(s){const a=ni(s.zone,'midboss');if(!a)return null;const twin=HAPIL_createMidbossDuoRC59(s,a,s.zone);s.enemies.push(a,...(twin?[twin]:[]));window.__HAPIL_RC69__?.completeMidbossWave(s);return a;},phase:(...a)=>MONGSE_enemyActivePhase(...a),wrathTick:(...a)=>MONGSE_tickSevenSinBossMechanics(...a),wrathSchedule:(...a)=>MONGSE_scheduleWrathBossSequence(...a),brain:(...a)=>MONGSE_tickBossCombatBrainSmartR1(...a),move:(...a)=>ft(...a),restoreEnemies:(...a)=>Ii(...a),blocked:ut,contains:Di,gap:(...a)=>MONGSE_tickBossGapCharge31226(...a),hitRadius:(...a)=>MONGSE_enemyHitRadius(...a)};`;
const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.webp':'image/webp','.wav':'audio/wav','.mp3':'audio/mpeg','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(file.endsWith('/assets/index-v31526.js')?fs.readFileSync(file,'utf8')+bridge:fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:!!cp.execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),status:'running',scope:'Staged real channel/save/boss-death/render paths; desktop/phone browser emulation',profiles:[]};const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const[name,width,height,mobile]of[['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1}),page=await context.newPage(),row={name,errors:[],missing:[],status:'running'};report.profiles.push(row);page.on('pageerror',e=>row.errors.push(e.stack||e.message));page.on('response',r=>{if(r.status()>=400)row.missing.push({url:r.url(),status:r.status()});});
 try{
 await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_RC133_NATIVE__?.installed);await page.keyboard.press('Escape');await page.evaluate(()=>window.__HAPIL_SAMONG_RC91__.unlock(null,'777'));await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();await page.locator('[data-game-mode-v31354="DREAM"]').click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__);for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
 row.native=await page.evaluate(()=>{
 const N=window.__HAPIL_RC133_NATIVE__,Q=window.__RC133_QA__,B=window.__HAPIL_RC86_BRIDGE__,U=window.__HAPIL_SAMONG_POLICY_RC133__,A=window.__HAPIL_SAMONG_RC91__,D=window.__HAPIL_CHANNEL_V31364__,H=window.__HAPIL_INNER_FINAL_RC133__,problems=[],details={};let checks=0;
 const test=(ok,label,extra)=>{checks++;if(!ok)problems.push({label,extra});},close=(a,b)=>Math.abs(a-b)<1e-6;
 const make=(zone='ep1b03',mode='DREAM')=>{const s=Q.initial();Object.assign(s,{zone,time:100,x:16,y:24,hp:240,maxHp:240,activeHeroId:'gunner',gameModeV31346:mode,samongUnlockedRC91:true,practiceV31329:false,awakeningUntil:0,encounterLockUntil31226:0,encounterWallUnlockAtV31227:0,encounterDialogue31226:null,timeStopUntil:0});return s;};
 const s=make();s.enemies=[B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03')];
 for(let i=1;i<=7;i++){s.time+=8;s.awakeningUntil=s.time;s.resonance=100;test(D.convert(s,s),'real normal EGO channel conversion '+i);test(U.status(s).count===(i===7?0:i),'counter consumes exactly on seventh '+i);}
 test(A.active(s)&&s.samongPassiveRC91.origin==='ego','seventh EGO activated live RC91');test(close(s.samongPassiveRC91.active,7)&&close(s.samongPassiveRC91.cooldown,77),'default 7/77');test(s.hp===240,'EGO activation does not heal');test(!A.tryRevive(s)&&!A.tryEgo(s),'same tick activation not duplicated');
 const reservation=make();reservation.enemies=s.enemies;A.tryEgo(reservation);reservation.samongPassiveRC91.cooldown=2;
 for(let i=0;i<7;i++){reservation.time+=8;reservation.awakeningUntil=reservation.time;reservation.resonance=100;D.convert(reservation,reservation);}
 test(U.status(reservation).count===7&&U.status(reservation).pending&&!A.active(reservation),'cooldown reserves seventh entry');
 const p={samongDuration:2,samongCooldown:3,samongPower:3,samongProtection:2,samongResonance:3};reservation.samongUpgradesRC133=p;const raw=N.save(reservation,'gunner',[],p,4),normal=N.normalize(raw);test(!!normal,'native save validates');test(normal?.samongRC91?.egoRC133?.pending===true,'reserved counter saved');test(normal?.passives?.samongDuration===2,'native save retains upgrade keys');
 const loaded=make();loaded.enemies=Q.restoreEnemies(normal);B.restoreEntry(loaded,normal);test(U.status(loaded).pending&&U.status(loaded).count===7,'native restore retains seventh reservation');test(loaded.samongUpgradesRC133.samongDuration===2,'native restore upgrade levels');A.advance(loaded,2.1,false);test(A.active(loaded)&&close(loaded.samongPassiveRC91.duration,9)&&close(loaded.samongPassiveRC91.cooldown,65.45),'reservation resumes after actual countdown with bounded upgrades');
 const lethal=make();lethal.enemies=s.enemies;lethal.hp=0;Object.assign(U.memory(lethal),{count:7,pending:true});test(A.tryRevive(lethal),'lethal boundary uses revival');test(U.status(lethal).count===0&&!A.tryEgo(lethal)&&lethal.samongPassiveRC91.activations===1,'lethal/seventh boundary atomic');
 const newRun=make();test(U.status(newRun).count===0,'new state clears run counter');
 const mid=[];for(const mode of ['STORY','DREAM'])for(const row of Q.midbossTemplates.filter(row=>row.zone!=='ep1a07')){
  const a=make(row.zone,mode);N.enter(a,row.zone,false);a.time=100;a.encounterLockUntil31226=0;a.encounterDialogue31226=null;
  let delayed=false;if(!a.enemies.some(e=>e.midboss)){a.enemies=[];delayed=true;Q.spawnMidbossWave(a);}N.midpoint(a);A.scaleEnemies(a);
  const leaders=a.enemies.filter(e=>e.midboss&&e.hp>0),entry={mode,zone:row.zone,delayed,count:leaders.length,actors:leaders.map(e=>({id:e.id,sprite:e.sprite,maxHp:e.maxHp}))};mid.push(entry);
  test(leaders.length===(mode==='DREAM'?3:2),'native initial/delayed midboss count '+mode+' '+row.zone,entry);
  test(new Set(leaders.map(e=>e.sprite)).size>=2,'distinct source sprites '+mode+' '+row.zone,entry);
  const survivor=leaders.at(-1);leaders[0].hp=0;a.enemies=a.enemies.filter(e=>e!==leaders[0]);N.midpoint(a);
  test(a.enemies.filter(e=>e.midboss).length===leaders.length-1,'death does not refill '+mode+' '+row.zone);
  const saved=N.normalize(N.save(a,'gunner',[],{},0)),loaded=make(row.zone,mode);loaded.enemies=Q.restoreEnemies(saved);B.restoreEntry(loaded,saved);A.scaleEnemies(loaded);
  test(loaded.enemies.filter(e=>e.midboss&&e.hp>0).length===leaders.length-1,'native load retains surviving count '+mode+' '+row.zone,{actors:loaded.enemies.filter(e=>e.midboss).map(e=>e.id),saved:saved?.midbossEncounterRC133});
  test(close(loaded.enemies.find(e=>e.id===survivor.id)?.maxHp,survivor.maxHp),'midboss HP not multiplied on load '+mode+' '+row.zone,{before:survivor.maxHp,after:loaded.enemies.find(e=>e.id===survivor.id)?.maxHp});
  test(N.foundation(a).regions.includes(row.zone),'visited region foundation '+mode+' '+row.zone);
 }
 details.midboss=mid;const legacy=make('ep1a07','STORY'),legacySave=N.normalize(N.save(legacy,'gunner',[],{},0));test(legacySave.zone==='ep1a08','removed ep1a07 save migrates to actual hospital route');
 const w=make('ep1b03','STORY'),a=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03');Object.assign(a,{x:w.x+.8,y:w.y,attackAt:0,recoverUntil:0,phaseTransitionUntil:0,atomicCastUntil31210:0,combatEntryGraceUntilV31239:0,staggerUntil:0});w.enemies=[a];const dest=N.destination(w,a);test(!!dest&&N.safeDestination(w,a,dest),'warp has native valid distant destination',dest);if(dest){w.pendingHits=[{id:999,shape:'circle',x:dest.x,y:dest.y,radius:2,damage:10,at:w.time+2}];test(!N.safeDestination(w,a,dest),'warp rejects actual pending area');w.pendingHits=[];N.warp(w,a);test(!!a.rc133Warp,'close player schedules warp');const b=B.cloneEnemy(a,'ep1b03');b.id='warp-second-fixture';b.x=w.x-.8;w.enemies.push(b);N.warp(w,b);test(!b.rc133Warp,'shared cooldown prevents simultaneous warp');w.time+=.56;N.warp(w,a);test(!a.rc133Warp&&Math.hypot(a.x-w.x,a.y-w.y)>=8,'warp safely commits');a.gapChargeV31226={phase:'dash'};w.pendingHits=[{sourceId:a.id,gapChargeV31226:true},{sourceId:a.id,id:'noncharge'}];Q.gap(w,a,0);test(!a.gapChargeV31226&&w.pendingHits.length===1&&w.pendingHits[0].id==='noncharge','boss gap charge cleared without cancelling noncharge');}
 const V=window.__HAPIL_BOSS_V31315__,charges=[];
 for(const {actor:template,zone}of V.rankedRows()){if(!V.profile(template,zone))continue;const st=make(zone,'STORY'),actor=B.cloneEnemy(template,zone);Object.assign(actor,{x:8,y:8,hp:100,staggerUntil:0,phaseTransitionUntil:0,dynamicBossReadyAtV31315:0});st.enemies=[actor];
  const result=V.enqueue(st,actor,'dash');test(result&&result.hit.dynamicBossModeV31315!=='dash','dynamic request converted to stationary coverage '+actor.id);
  const x=actor.x,y=actor.y;V.onImpact(st,{...result.hit,dynamicBossModeV31315:'dash'});st.time+=1;V.tick(st);test(actor.x===x&&actor.y===y&&V.activeDashes(st)===0,'legacy dynamic impact cannot move '+actor.id);charges.push(actor.id);
 }
 details.stationaryDynamicPatterns=charges;
 const wrath=make('ep1b07','STORY'),wa=B.cloneEnemy(B.actor('ep1b07','b07-boss'),'ep1b07');wa.x=8;wa.y=8;wrath.enemies=[wa];const wx=wa.x,wy=wa.y;
 const ignition=Q.wrathSchedule(wrath,wa,Q.phase(wa),wrath.time+.4,{sevenSinMechanic:'wrath-ignite',telekineticRain:true});test(!!ignition&&wrath.pendingHits.includes(ignition),'wrath preserves committed nonmoving ignition line');wrath.time=wa.wrathDashAt+.01;Q.wrathTick(wrath);test(wa.x===wx&&wa.y===wy&&wa.wrathRageUntil>wrath.time,'wrath ignition/rage cadence without self charge');
 for(const flags of [{episodeCosmicFinalV387:true},{dreamCosmicTrialV31346:2},{rc133InnerBoss:true}]){const st=make(),actor=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03');Object.assign(actor,flags,{x:8,y:8});st.enemies=[actor];N.pin(actor);actor.x=9;actor.y=9;const result=Q.brain(st,actor,.1);window.__HAPIL_STAND_V31335__.tick(st,.1);Q.move(st.zone,actor,{x:12,y:12});N.warp(st,actor);test(actor.x===8&&actor.y===8&&!actor.rc133Warp&&result.moveScale===0,'cosmic/persona stationary core '+JSON.stringify(flags));}
 const humanoid=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');const body=[];for(let phase=0;phase<=3;phase++){humanoid.fixedPhase=phase;humanoid.currentPhase=phase;body.push({phase,radius:Q.hitRadius(humanoid),profile:window.__HAPIL_STAND_V31335__.profile(humanoid)});}test(body.every(row=>row.radius===.72&&row.profile?.human===body[0].profile?.human),'humanoid core same target/radius through Stand phases',body.map(({phase,radius})=>({phase,radius})));details.humanoid=body.map(({phase,radius})=>({phase,radius}));
 const h=make('cult04'),leader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');leader.hp=0;h.enemies=[leader];test(H.beforeDeath(h,leader),'actual cult leader id admits hidden route');test(h.innerFinalRC133?.phase==='reveal'&&!!H.boss(h),'hidden live actor created');const bound=H.growth(h,{infinitePower:1e100,samongDuration:9999});test(bound<=2.1,'inner persona growth bounded');const hs=N.save(h,'gunner',[],{},0),hn=N.normalize(hs),hr=make('cult04');hr.enemies=Q.restoreEnemies(hn);B.restoreEntry(hr,hn);test(H.active(hr)&&hr.enemies.filter(e=>e.id===H.id).length===1,'hidden native save/restore one actor');
 h.innerFinalRC133.intro=0;h.innerFinalRC133.shotDelay=0;H.tick(h,.016);const shots=h.hostileProjectiles.filter(e=>e.rc133InnerShot);test(shots.length===6,'gunner traits create bounded six shots');test(shots.every(q=>Math.abs(Math.hypot(q.vx,q.vy)-3.6)<1e-6&&q.radius<=.32&&q.collisionDisabledUntil31219>=h.time+.65),'inner shots native windup and bounded speed');
 const innerTraits=[];for(const hero of A.heroes){const st=make('cult04'),dead=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');st.activeHeroId=hero;dead.hp=0;st.enemies=[dead];H.start(st,dead);st.innerFinalRC133.intro=0;st.innerFinalRC133.shotDelay=0;H.tick(st,.016);const shots=st.hostileProjectiles.filter(q=>q.rc133InnerShot);innerTraits.push({hero,count:shots.length,speed:Math.hypot(shots[0]?.vx,shots[0]?.vy),color:shots[0]?.color});test(shots.length===H.traits[hero].count&&shots.every(q=>q.damage<=20&&q.radius<=.32&&Math.hypot(q.vx,q.vy)<=4.8),'hero persona borrows bounded native trait '+hero,innerTraits.at(-1));
  const previous=st.innerFinalRC133.cycle;st.hostileProjectiles.push(...Array.from({length:72-shots.length},()=>({})));st.innerFinalRC133.shotDelay=0;H.tick(st,.016);test(st.hostileProjectiles.length===72&&st.innerFinalRC133.cycle===previous,'persona atomic projectile cap '+hero);
  const pending=st.innerFinalRC133.awakeningCooldown;st.timeStopUntil=st.time+10;H.tick(st,.1);test(st.innerFinalRC133.awakeningCooldown===pending,'persona timers pause during time stop '+hero);
 }
 details.innerTraits=innerTraits;test(new Set(innerTraits.map(row=>JSON.stringify([row.count,row.speed,row.color]))).size===8,'eight distinct hero trait profiles');
 const completed=make('cult04'),doneLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');doneLeader.hp=0;completed.enemies=[doneLeader];H.start(completed,doneLeader);const inner=H.boss(completed);completed.pendingHits.push({sourceId:H.id,damage:10});completed.hostileProjectiles.push({sourceId:H.id,damage:10});inner.hp=0;H.beforeDeath(completed,inner);test(completed.innerFinalRC133.phase==='complete'&&completed.pendingHits.length===0&&completed.hostileProjectiles.length===0,'inner death cleans actual owned attacks');const completeSave=N.normalize(N.save(completed,'gunner',[],{},0)),resumed=make('cult04');resumed.enemies=Q.restoreEnemies(completeSave);B.restoreEntry(resumed,completeSave);test(resumed.bossDefeated&&!H.boss(resumed)&&H.mood(resumed)==='normal','completed save cannot resurrect inner boss');
 const storyLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04'),story=make('cult04','STORY');storyLeader.hp=0;test(!H.beforeDeath(story,storyLeader)&&!story.innerFinalRC133,'Story cult leader route preserved');
 const moods=[];for(const [player,boss,expected]of[[false,false,'normal'],[true,false,'player'],[false,true,'boss'],[true,true,'opposition']]){h.samongPassiveRC91={active:player?7:0,cooldown:77,duration:7,heroId:'gunner'};h.innerFinalRC133.awake=boss?7:0;test(H.mood(h)===expected,'four-state mood '+expected);moods.push(expected);}details.moods=moods;
 h.hp=0;test(H.mood(h)==='normal','death clears composition eligibility');h.hp=240;h.innerFinalRC133.phase='complete';test(H.mood(h)==='normal','completion clears composition eligibility');h.zone='ep1b03';test(H.mood(h)==='normal','other zone composition normal');
 // Deterministic draw surfaces isolate the compositor and prove context restoration.
 const pixel=[];for(const [p,b,expected]of[[false,false,'normal'],[true,false,'player'],[false,true,'boss'],[true,true,'opposition']]){h.zone='cult04';h.innerFinalRC133.phase='fight';h.innerFinalRC133.awake=b?7:0;h.samongPassiveRC91.active=p?7:0;const c=document.createElement('canvas');c.width=200;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#5299cc';ctx.fillRect(0,0,200,100);ctx.filter='none';H.compose(ctx,h,c);const left=Array.from(ctx.getImageData(40,50,1,1).data),right=Array.from(ctx.getImageData(160,50,1,1).data);test(ctx.filter==='none'&&ctx.globalCompositeOperation==='source-over','compositor no filter leak '+expected);if(expected==='player')test(left[0]===left[1]&&left[1]===left[2],'whole player grayscale');if(expected==='boss')test(left[0]>left[1]&&left[0]>left[2],'whole boss red');if(expected==='opposition')test(left[0]===left[1]&&right[0]>right[1],'opposed halves');pixel.push({expected,left,right});}details.pixel=pixel;
 window.__RC133_FIXTURES__={hidden:h,ego:s};return {checks,problems,details};
 });assert.deepEqual(row.native.problems,[]);
 // Staged resource pickup, then the ordinary React settings/growth UI.
 await page.evaluate(()=>{const b=window.__HAPIL_CONTROLS_V31329__.binding,s=b.state.current;b.actions.dismiss();s.egoDrops.push({id:s.fxSerial++,x:s.x,y:s.y,born:s.time,amount:3});});await page.waitForFunction(()=>window.__HAPIL_CONTROLS_V31329__.binding.shards.current>=3);await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.actions.settings());await page.getByRole('button',{name:'공명 강화',exact:true}).click();assert.equal(await page.locator('[data-upgrade-category="samongUpgrade"]:visible').count(),1);assert.equal(await page.locator('[data-samong-upgrade]').count(),5);const before=await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.shards.current);await page.locator('[data-samong-upgrade="samongDuration"]').click();await page.waitForFunction(()=>window.__HAPIL_CONTROLS_V31329__.binding.passives.current.samongDuration===1);assert.equal(await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.shards.current),before-1);row.upgradeUI={ordinaryReactPanel:true,stagedResourcePickup:true,tracks:5,purchased:'samongDuration',cost:1};await page.evaluate(()=>{const b=window.__HAPIL_CONTROLS_V31329__.binding;b.actions.dismiss();window.__HAPIL_MODES_V31346__.set('STORY',b.state.current);});await page.waitForTimeout(200);for(let i=0;i<16&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.actions.settings());await page.getByRole('button',{name:'공명 강화',exact:true}).click();assert.equal(await page.locator('[data-upgrade-category="samongUpgrade"]').count(),0);row.upgradeUI.storyHidden=true;await page.evaluate(()=>{const b=window.__HAPIL_CONTROLS_V31329__.binding;b.actions.dismiss();window.__HAPIL_MODES_V31346__.set('DREAM',b.state.current);});
 // Exercise the installed live React enemy-death closure; the QA handler explicitly forces boss HP=0.
 row.liveHidden=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;window.__MONGSE_QA_API__.stageV3128BossShowcase('cult04');s.innerFinalRC133=null;const dead=window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();return{dead,phase:s.innerFinalRC133?.phase,id:window.__HAPIL_INNER_FINAL_RC133__.boss(s)?.id};});assert.equal(row.liveHidden.phase,'reveal','live native cult death enters hidden phase');assert.equal(row.liveHidden.id,'inner-evil-rc133');
 row.liveCompletion=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();return {phase:s.innerFinalRC133?.phase,bossDefeated:s.bossDefeated,liveInner:!!window.__HAPIL_INNER_FINAL_RC133__.boss(s),cleared:window.__HAPIL_RC86_BRIDGE__.zoneCombatCleared(s,s.zone),mood:window.__HAPIL_INNER_FINAL_RC133__.mood(s)};});assert.deepEqual(row.liveCompletion,{phase:'complete',bossDefeated:true,liveInner:false,cleared:true,mood:'normal'});
 for(const mode of ['normal','player','boss','opposition']){await page.evaluate(mode=>{const s=window.__RC133_FIXTURES__.hidden;s.hp=240;s.innerFinalRC133.phase='fight';s.innerFinalRC133.awake=['boss','opposition'].includes(mode)?7:0;s.samongPassiveRC91.active=['player','opposition'].includes(mode)?7:0;window.__RC133_FIXED_STATE__=s;},mode);await page.waitForTimeout(200);await page.screenshot({path:path.join(out,name+'-inner-'+mode+'.png')});}
 await page.evaluate(()=>{delete window.__RC133_FIXED_STATE__;});assert.deepEqual(row.errors,[]);assert.deepEqual(row.missing,[]);row.status='passed';
 }catch(e){row.status='failed';row.error=String(e.stack||e);}finally{save();console.log('RC133_BROWSER_PROFILE',JSON.stringify({name,status:row.status,error:row.error,native:row.native,liveHidden:row.liveHidden,errors:row.errors,missing:row.missing}));await context.close();}
}
 report.status=report.profiles.every(r=>r.status==='passed')?'passed':'failed';
}finally{save();await browser?.close();server.close();process.exitCode=report.status==='passed'?0:1;}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
