'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results'),'rc130-browser');fs.mkdirSync(out,{recursive:true});
const bridge='\nwindow.__RC130_TEST__={initial:oi,project:G,queue:MONGSE_queueImage,projectile:(...a)=>Jn(...a),effect:(...a)=>Gn(...a)};';
const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.webp':'image/webp','.wav':'audio/wav','.woff2':'font/woff2','.svg':'image/svg+xml','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{try{const f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');const b=fs.readFileSync(f);res.end(f.endsWith('/assets/index-v31526.js')?b.toString()+bridge:b);}catch{res.writeHead(404).end();}});
const report={commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),status:'running',profiles:[],scope:'Three normal UI startup/movement observations; separate staged native barrage/melee/damage fixtures and real Canvas cap stress. Not full campaigns or subjective audio listening.'};
const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,page;
try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const[name,width,height,mobile]of[['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1});page=await context.newPage();const row={name,errors:[],httpErrors:[]};report.profiles.push(row);save();
 page.on('pageerror',e=>{row.errors.push(e.stack||e.message);console.error('RC130_JS_ERROR',e.stack||e.message);});page.on('response',r=>{if(r.status()>=400)row.httpErrors.push({url:r.url(),status:r.status()});});
 await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForTimeout(1500);row.bootstrap=await page.evaluate(()=>({keys:Object.keys(window).filter(k=>/HAPIL_(?:RC91|RC95|RC130|EXIT|RC71|DANMAKU_HUD)/.test(k)),rc130:window.__HAPIL_RC130_AUDIT__?.(),errors:window.__HAPIL_STARTUP_DIAGNOSTICS__}));save();
 await page.waitForFunction(()=>window.__HAPIL_RC130_INSTALLED__&&window.__HAPIL_DANMAKU_HUD_RC129__?.installed,{},{timeout:30000});
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();assert.equal(await page.locator('[data-game-mode-v31354="HELL"]:visible').count(),0);await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__);
 for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
 const live=()=>page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;return{x:s.x,y:s.y,time:s.time,hp:s.hp,zone:s.zone,mode:s.gameModeV31346,speed:s.rc127MovementSpeed,vx:s.moveVx,vy:s.moveVy,audit:window.__HAPIL_RC130_AUDIT__()};});
 const first=await live();await page.keyboard.down('ArrowRight');await page.waitForTimeout(550);await page.keyboard.up('ArrowRight');await page.keyboard.down('a');await page.waitForTimeout(400);await page.keyboard.up('a');await page.waitForTimeout(2200);const last=await live();
 assert(last.time>first.time&&Number.isFinite(last.hp));assert(Math.abs(last.speed-4.75*1.21*1.126)<1e-8);assert(last.audit.installed&&last.audit.audio.installed);row.startup={first,last,usedProgressCheats:false};await page.screenshot({path:path.join(out,name+'-natural.png')});save();
 row.native=await page.evaluate(async()=>{
  const T=window.__RC130_TEST__,B=window.__HAPIL_RC86_BRIDGE__,N=window.__HAPIL_RC95_NATIVE__,F=window.__HAPIL_COMBAT_FLOW_RC95__,V=window.__HAPIL_VISUAL_RC130__,A=window.__HAPIL_AUDIO_RC130__,problems=[];
  const check=(x,m)=>{if(!x)problems.push(m);};
  const s=T.initial(),a=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03');Object.assign(s,{zone:'ep1b03',time:100,x:24,y:23,hp:240,maxHp:240,invulnerableUntil:0,activeHeroId:'hwando',gameModeV31346:'STORY',practiceV31329:false,timeStopUntil:0,enemySkillsSuppressedUntilV31309:0});Object.assign(a,{x:8,y:8,hp:a.maxHp,humanPhase0:false,fixedPhase:1,currentPhase:1,attackAt:0,attackStarted:0,readyAt:0,patternReadyAt:0,recoverUntil:0,atomicCastUntil31210:0,staggerUntil:0,invulnerableUntil:0,phaseTransitionUntil:0,combatEntryGraceUntilV31239:0});s.enemies=[a];F.tick(s,N,.016);
  const shots=s.hostileProjectiles.filter(q=>q.rc129Plan);check(shots.length===6,'RC129 STORY corridor volley preserved');const p=shots[0];if(!p)return{problems,shots:s.hostileProjectiles};s.time=Math.max(...shots.map(q=>q.motionReleaseAt31219))+.5;for(const q of shots){q.x+=q.vx*(s.time-q.motionReleaseAt31219);q.y+=q.vy*(s.time-q.motionReleaseAt31219);}
  const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=600;const ctx=canvas.getContext('2d'),cache={},draws=[],original=ctx.drawImage;ctx.drawImage=function(...args){const o=args.length===9?5:args.length===5?1:-1;if(o>=0){const m=this.getTransform(),w=Math.abs(args[o+2]),h=Math.abs(args[o+3]),bound=V.bounds(canvas);draws.push({width:(Math.abs(m.a)*w+Math.abs(m.c)*h)/bound.width,height:(Math.abs(m.b)*w+Math.abs(m.d)*h)/bound.height});}return original.apply(this,args);};
  const paths=[...new Set(shots.flatMap(q=>[q.rc126CommonSprite,q.danmakuArt31219,q.sprite,q.fallbackSprite]).filter(Boolean))];for(const path of paths){const im=T.queue(cache,path,'eager');if(im?.decode)await im.decode();}
  for(let n=0;n<3;n++){for(const q of shots)T.projectile(ctx,cache,q,s.time,{});await new Promise(r=>setTimeout(r,100));}
  check(draws.length>0,'real native barrage renderer issued decoded image draws');check(draws.every(r=>r.width<=.2000001&&r.height<=.2000001),'native barrage dimensions within 20%');const nativeDraws=draws.slice();
  const im=T.queue(cache,paths[0],'eager');await im.decode();const stress={...p,id:'rc130-explicit-canvas-stress'},before=V.snapshot().stats.cappedDraws;draws.length=0;
  ctx.save();ctx.translate(500,300);ctx.rotate(Math.PI/4);V.drawProjectile((c)=>c.drawImage(im,-5000,-3000,10000,6000),ctx,cache,stress,s.time,{});ctx.restore();
  check(V.snapshot().stats.cappedDraws>before&&draws.every(r=>r.width<=.2000001&&r.height<=.2000001),'oversized rotated Canvas image bounded');check(V.contactRadius(s,stress,500)<=V.snapshot(stress).layout.halfMinor,'capped collision is no larger than its minor footprint');
  const mob=(B.zoneActors('dist00')||[]).find(e=>!e.boss&&!e.midboss)||{id:'rc130-staged-melee',kind:'zombie'},meleePath=window.__MONGSE_ENEMY_COMBAT_V31237__?.visual?.(mob,{role:'melee'});
  check(!!meleePath,'native melee asset resolver');let meleeResult=null;
  if(meleePath){const mi=T.queue(cache,meleePath,'eager');await mi.decode();const e={id:'rc130-native-melee',shape:'circle',sourceName:mob.id,attackerId:mob.id,x:16,y:16,tx:19,ty:19,born:s.time,life:.3,radius:1.8,sprite:meleePath,normalMonsterEffect:true,enemyMeleeTelegraphV31237:true,enemyRenderLifetimeV31237:.3};const e0=V.stationary(e,s.time+.05);T.effect(ctx,cache,e,s.time+.05,{});e.x=19;e.y=20;const e1=V.stationary(e,s.time+.2);T.effect(ctx,cache,e,s.time+.2,{});const dead=V.stationary(e,s.time+.31);check(e0.effect.x===e1.effect.x&&e0.effect.y===e1.effect.y&&dead.expired,'melee origin does not drift and expires');const E=window.__HAPIL_EXIT_V31334__;check(!!E&&E.captureRenderedEffect(e)===false,'actual generic exit rejects melee');meleeResult={path:meleePath,first:{x:e0.effect.x,y:e0.effect.y},last:{x:e1.effect.x,y:e1.effect.y},expired:dead.expired,exitHook:window.__HAPIL_RC130_AUDIT__().exitHook};}
  const core=window.__HAPIL_COMBAT_CORE_V31401__,beforeHurt=A.snapshot().stats.allyHurtRequests,hp=s.hp;core.player(s,30,a.x,a.y,{id:'rc130-staged-native-contact',sourceId:a.id,damage:30});const delivered=[];A.tick(s,{sound:true,sfxVolume:1},(...args)=>delivered.push(args),true);check(s.hp<hp,'real player reducer accepted contact');check(A.snapshot().stats.allyHurtRequests>beforeHurt,'native damage event routed to allied hurt');check(delivered.some(v=>v[0]===A.snapshot(s).neutralHurt),'hurt audio requested via priority channel');
  const base=B.renderFrame;B.renderFrame=function(...args){if(window.__RC130_FIXED_STATE__){args[1]=window.__RC130_FIXED_STATE__;args[3]=N.heroes.find(h=>h.id==='hwando')||args[3];}return base.apply(this,args);};window.__RC130_FIXED_STATE__=s;
  return{problems,shots:shots.length,nativeDraws,stress:V.snapshot(stress).layout,melee:meleeResult,audio:A.snapshot(s),audit:window.__HAPIL_RC130_AUDIT__(),scope:'staged native scene and explicit Canvas stress; not natural survival'};
 });
 save();console.log('RC130_NATIVE_RESULT',JSON.stringify({name,...row.native}));assert.deepEqual(row.native.problems,[]);await page.waitForTimeout(500);await page.screenshot({path:path.join(out,name+'-native-barrage.png')});await page.evaluate(()=>delete window.__RC130_FIXED_STATE__);assert.deepEqual(row.errors,[]);assert.deepEqual(row.httpErrors,[]);await context.close();save();
}
report.status='passed';console.log('RC130_BROWSER_RESULT',JSON.stringify({status:report.status,profiles:report.profiles.length,scope:report.scope}));
}catch(e){report.status='failed';report.error=String(e.stack||e);if(page)try{await page.screenshot({path:path.join(out,'failure.png')});}catch{}console.error(e);process.exitCode=1;}
finally{save();await browser?.close();server.close();}
})();
