'use strict';
// Native staged fixtures. Every forced health/time/progress change is deliberate test setup.
// These are browser emulations; no full natural campaign or physical phone claim.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'..'),out=path.join(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results'),'rc133');fs.mkdirSync(out,{recursive:true});
const bridge=`\nconst rc133Frame=$n;$n=function(...args){if(window.__RC133_FIXED_STATE__){args[1]=window.__RC133_FIXED_STATE__;args[3]=F.find(h=>h.id===args[1].activeHeroId)||args[3];}return rc133Frame(...args);};window.__RC133_QA__={initial:oi,midbossTemplates:Object.entries(N).flatMap(([zone,z])=>(z.enemies??[]).filter(a=>a.midboss).map(a=>({zone,id:a.id}))),restoreEnemies:(...a)=>Ii(...a),blocked:ut,contains:Di,gap:(...a)=>MONGSE_tickBossGapCharge31226(...a),hitRadius:(...a)=>MONGSE_enemyHitRadius(...a)};`;
const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.webp':'image/webp','.wav':'audio/wav','.mp3':'audio/mpeg','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(file.endsWith('/assets/index-v31526.js')?fs.readFileSync(file,'utf8')+bridge:fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:!!cp.execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),status:'running',scope:'Staged real channel/save/boss-death/render paths; desktop/phone browser emulation',profiles:[]};const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const[name,width,height,mobile]of[['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1}),page=await context.newPage(),row={name,errors:[],missing:[],status:'running'};report.profiles.push(row);page.on('pageerror',e=>row.errors.push(e.stack||e.message));page.on('response',r=>{if(r.status()>=400)row.missing.push({url:r.url(),status:r.status()});});
 try{
 await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_RC133_NATIVE__?.installed);await page.keyboard.press('Escape');await page.evaluate(()=>window.__HAPIL_SAMONG_RC91__.unlock(null,'777'));await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();await page.locator('[data-game-mode-v31354="DREAM"]').click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__);for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
 row.native=await page.evaluate(()=>{
 const N=window.__HAPIL_RC133_NATIVE__,Q=window.__RC133_QA__,B=window.__HAPIL_RC86_BRIDGE__,U=window.__HAPIL_SAMONG_POLICY_RC133__,A=window.__HAPIL_SAMONG_RC91__,D=window.__HAPIL_CHANNEL_V31364__,H=window.__HAPIL_INNER_FINAL_RC133__,problems=[],details={};let checks=0;
 const test=(ok,label,extra)=>{checks++;if(!ok)problems.push({label,extra});},close=(a,b)=>Math.abs(a-b)<1e-6;
 const make=(zone='ep1b03',mode='DREAM')=>{const s=Q.initial();Object.assign(s,{zone,time:100,x:16,y:24,hp:240,maxHp:240,activeHeroId:'gunner',gameModeV31346:mode,samongUnlockedRC91:true,practiceV31329:false,awakeningUntil:0,encounterLockUntil31226:0,encounterWallUnlockAtV31227:0,encounterDialogue31226:null,timeStopUntil:0});return s;};
 const s=make();s.enemies=[B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03')];
 for(let i=1;i<=7;i++){s.time+=8;s.awakeningUntil=s.time;s.resonance=100;test(D.convert(s,s),'real normal EGO channel conversion '+i);test(U.status(s).count===(i===7?0:i),'counter consumes exactly on seventh '+i);}
 test(A.active(s)&&s.samongPassiveRC91.origin==='ego','seventh EGO activated live RC91');test(close(s.samongPassiveRC91.active,7)&&close(s.samongPassiveRC91.cooldown,77),'default 7/77');test(s.hp===240,'EGO activation does not heal');test(!A.tryRevive(s)&&!A.tryEgo(s),'same tick activation not duplicated');
 const reservation=make();reservation.enemies=s.enemies;A.tryEgo(reservation);reservation.samongPassiveRC91.cooldown=2;
 for(let i=0;i<7;i++){reservation.time+=8;reservation.awakeningUntil=reservation.time;reservation.resonance=100;D.convert(reservation,reservation);}
 test(U.status(reservation).count===7&&U.status(reservation).pending&&!A.active(reservation),'cooldown reserves seventh entry');
 const p={samongDuration:2,samongCooldown:3,samongPower:3,samongProtection:2,samongResonance:3};reservation.samongUpgradesRC133=p;const raw=N.save(reservation,'gunner',[],p,4),normal=N.normalize(raw);test(!!normal,'native save validates');test(normal?.samongRC91?.egoRC133?.pending===true,'reserved counter saved');test(normal?.passives?.samongDuration===2,'native save retains upgrade keys');
 const loaded=make();loaded.enemies=Q.restoreEnemies(normal);B.restoreEntry(loaded,normal);test(U.status(loaded).pending&&U.status(loaded).count===7,'native restore retains seventh reservation');test(loaded.samongUpgradesRC133.samongDuration===2,'native restore upgrade levels');A.advance(loaded,2.1,false);test(A.active(loaded)&&close(loaded.samongPassiveRC91.duration,9)&&close(loaded.samongPassiveRC91.cooldown,65.45),'reservation resumes after actual countdown with bounded upgrades');
 const lethal=make();lethal.enemies=s.enemies;lethal.hp=0;Object.assign(U.memory(lethal),{count:7,pending:true});test(A.tryRevive(lethal),'lethal boundary uses revival');test(U.status(lethal).count===0&&!A.tryEgo(lethal)&&lethal.samongPassiveRC91.activations===1,'lethal/seventh boundary atomic');
 const newRun=make();test(U.status(newRun).count===0,'new state clears run counter');
 const mid=[];const midTemplate=Q.midbossTemplates[0];for(const mode of ['STORY','DREAM']){const a=make(midTemplate.zone,mode),first=B.cloneEnemy(B.actor(midTemplate.zone,midTemplate.id),midTemplate.zone);a.enemies=[first];const twin=window.__HAPIL_EPISODE1_RC59__.makeMidbossDuo(a,first,midTemplate.zone);if(twin)a.enemies.push(twin);const candidates=a.enemies.filter(e=>e.midboss);N.midpoint(a);const leaders=a.enemies.filter(e=>e.midboss);mid.push({mode,zone:midTemplate.zone,before:candidates.length,after:leaders.length,actors:leaders.map(e=>({id:e.id,sprite:e.sprite}))});test(leaders.length===(mode==='DREAM'?3:2),'midboss count '+mode,mid.at(-1));test(new Set(leaders.map(e=>e.sprite)).size>=2,'midboss distinct source art '+mode);test(N.foundation(a).regions.includes(midTemplate.zone),'visited region foundation '+mode);}
 details.midboss=mid;
 const w=make('ep1b03','STORY'),a=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03');Object.assign(a,{x:w.x+.8,y:w.y,attackAt:0,recoverUntil:0,phaseTransitionUntil:0,atomicCastUntil31210:0,combatEntryGraceUntilV31239:0,staggerUntil:0});w.enemies=[a];const dest=N.destination(w,a);test(!!dest&&N.safeDestination(w,a,dest),'warp has native valid distant destination',dest);if(dest){w.pendingHits=[{id:999,shape:'circle',x:dest.x,y:dest.y,radius:2,damage:10,at:w.time+2}];test(!N.safeDestination(w,a,dest),'warp rejects actual pending area');w.pendingHits=[];N.warp(w,a);test(!!a.rc133Warp,'close player schedules warp');const b=B.cloneEnemy(a,'ep1b03');b.id='warp-second-fixture';b.x=w.x-.8;w.enemies.push(b);N.warp(w,b);test(!b.rc133Warp,'shared cooldown prevents simultaneous warp');w.time+=.56;N.warp(w,a);test(!a.rc133Warp&&Math.hypot(a.x-w.x,a.y-w.y)>=8,'warp safely commits');a.gapChargeV31226={phase:'dash'};Q.gap(w,a,0);test(!a.gapChargeV31226,'boss gap charge cleared');}
 const h=make('cult04'),leader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');leader.hp=0;h.enemies=[leader];test(H.beforeDeath(h,leader),'actual cult leader id admits hidden route');test(h.innerFinalRC133?.phase==='reveal'&&!!H.boss(h),'hidden live actor created');const bound=H.growth(h,{infinitePower:1e100,samongDuration:9999});test(bound<=2.1,'inner persona growth bounded');const hs=N.save(h,'gunner',[],{},0),hn=N.normalize(hs),hr=make('cult04');hr.enemies=Q.restoreEnemies(hn);B.restoreEntry(hr,hn);test(H.active(hr)&&hr.enemies.filter(e=>e.id===H.id).length===1,'hidden native save/restore one actor');
 h.innerFinalRC133.intro=0;h.innerFinalRC133.shotDelay=0;H.tick(h,.016);const shots=h.hostileProjectiles.filter(e=>e.rc133InnerShot);test(shots.length===6,'gunner traits create bounded six shots');test(shots.every(q=>Math.abs(Math.hypot(q.vx,q.vy)-3.6)<1e-6&&q.radius<=.32&&q.collisionDisabledUntil31219>=h.time+.65),'inner shots native windup and bounded speed');
 const moods=[];for(const [player,boss,expected]of[[false,false,'normal'],[true,false,'player'],[false,true,'boss'],[true,true,'opposition']]){h.samongPassiveRC91={active:player?7:0,cooldown:77,duration:7,heroId:'gunner'};h.innerFinalRC133.awake=boss?7:0;test(H.mood(h)===expected,'four-state mood '+expected);moods.push(expected);}details.moods=moods;
 h.hp=0;test(H.mood(h)==='normal','death clears composition eligibility');h.hp=240;h.innerFinalRC133.phase='complete';test(H.mood(h)==='normal','completion clears composition eligibility');h.zone='ep1b03';test(H.mood(h)==='normal','other zone composition normal');
 // Deterministic draw surfaces isolate the compositor and prove context restoration.
 const pixel=[];for(const [p,b,expected]of[[false,false,'normal'],[true,false,'player'],[false,true,'boss'],[true,true,'opposition']]){h.zone='cult04';h.innerFinalRC133.phase='fight';h.innerFinalRC133.awake=b?7:0;h.samongPassiveRC91.active=p?7:0;const c=document.createElement('canvas');c.width=200;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#5299cc';ctx.fillRect(0,0,200,100);ctx.filter='none';H.compose(ctx,h,c);const left=Array.from(ctx.getImageData(40,50,1,1).data),right=Array.from(ctx.getImageData(160,50,1,1).data);test(ctx.filter==='none'&&ctx.globalCompositeOperation==='source-over','compositor no filter leak '+expected);if(expected==='player')test(left[0]===left[1]&&left[1]===left[2],'whole player grayscale');if(expected==='boss')test(left[0]>left[1]&&left[0]>left[2],'whole boss red');if(expected==='opposition')test(left[0]===left[1]&&right[0]>right[1],'opposed halves');pixel.push({expected,left,right});}details.pixel=pixel;
 window.__RC133_FIXTURES__={hidden:h,ego:s};return {checks,problems,details};
 });assert.deepEqual(row.native.problems,[]);
 // Exercise the installed live React enemy-death closure; the QA handler explicitly forces boss HP=0.
 row.liveHidden=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;window.__MONGSE_QA_API__.stageV3128BossShowcase('cult04');s.innerFinalRC133=null;const dead=window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();return{dead,phase:s.innerFinalRC133?.phase,id:window.__HAPIL_INNER_FINAL_RC133__.boss(s)?.id};});assert.equal(row.liveHidden.phase,'reveal','live native cult death enters hidden phase');assert.equal(row.liveHidden.id,'inner-evil-rc133');
 for(const mode of ['normal','player','boss','opposition']){await page.evaluate(mode=>{const s=window.__RC133_FIXTURES__.hidden;s.hp=240;s.innerFinalRC133.phase='fight';s.innerFinalRC133.awake=['boss','opposition'].includes(mode)?7:0;s.samongPassiveRC91.active=['player','opposition'].includes(mode)?7:0;window.__RC133_FIXED_STATE__=s;},mode);await page.waitForTimeout(200);await page.screenshot({path:path.join(out,name+'-inner-'+mode+'.png')});}
 await page.evaluate(()=>{delete window.__RC133_FIXED_STATE__;});assert.deepEqual(row.errors,[]);assert.deepEqual(row.missing,[]);row.status='passed';
 }catch(e){row.status='failed';row.error=String(e.stack||e);}finally{save();console.log('RC133_BROWSER_PROFILE',JSON.stringify({name,status:row.status,error:row.error,native:row.native,liveHidden:row.liveHidden,errors:row.errors,missing:row.missing}));await context.close();}
}
 report.status=report.profiles.every(r=>r.status==='passed')?'passed':'failed';
}finally{save();await browser?.close();server.close();process.exitCode=report.status==='passed'?0:1;}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
