'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results/rc131-browser'));fs.mkdirSync(out,{recursive:true});
const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.wav':'audio/wav','.mp3':'audio/mpeg','.ogg':'audio/ogg','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{try{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();let bytes=fs.readFileSync(file);if(file.endsWith('/assets/index-v31526.js')){let code=bytes.toString();const anchor='    MONGSE_unlockAudio = (0, l.useCallback)';assert.equal(code.split(anchor).length,2);code=code.replace(anchor,'    RC131_audioProbe = (window.__RC131_PLAY__=We,window.__RC131_BRIDGE_REF__=HAPIL_combatAudioBridgeRef),\n'+anchor);bytes=Buffer.from(code+'\nwindow.__RC131_RESOLVER__=MONGSE_resolveHeroSfxV31233;');}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(bytes);}catch(e){res.writeHead(404).end(String(e));}});
function probe(){const play=HTMLMediaElement.prototype.play,elements=new Set(),events=[];let max=0;const owns=e=>/\/audio\/rc131\/|\/combat-audio\/v1\/audio\/effect-/.test(e.src),sample=()=>{const active=[...elements].filter(e=>owns(e)&&((!e.paused&&!e.ended)||e.__hapilCombatPending));max=Math.max(max,active.length);return active.length;};HTMLMediaElement.prototype.play=function(...a){elements.add(this);sample();const value=play.apply(this,a);value?.then?.(()=>{events.push({src:this.src,accepted:true,volume:this.volume});sample();},err=>events.push({src:this.src,accepted:false,error:String(err)}));return value;};setInterval(sample,10);window.__RC131_MEDIA__={elements,events,snapshot:()=>({max,active:sample(),events:events.slice(),clips:[...elements].filter(owns).map(e=>({src:e.src,paused:e.paused,ended:e.ended,pending:!!e.__hapilCombatPending,ready:e.readyState,volume:e.volume,duration:e.duration}))})};}
const report={status:'running',sourceCommit:process.env.HAPIL_SOURCE_SHA||null,profiles:[],scope:'3 unchanged startup observations plus staged native-audio cue admission/decoding/mute tests; not human listening or a complete campaign'};const save=()=>fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));
async function run(){await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});for(const[name,width,height,mobile]of[['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){
 const ctx=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile}),page=await ctx.newPage(),errors=[],failed=[];page.setDefaultTimeout(20000);await page.addInitScript(probe);page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});
 await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_AUDIO_CUES_RC131__&&window.__HAPIL_RC130_NATIVE_INSTALLED__);await page.keyboard.press('Escape');await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();assert.equal(await page.locator('[data-game-mode-v31354="HELL"]:visible').count(),0);await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__&&window.__RC131_PLAY__);
 await page.evaluate(()=>{const b=__HAPIL_CONTROLS_V31329__.binding;b.setSettings(c=>({...c,sound:true,sfxVolume:.6,music:true,bgmVolume:.2}));__HAPIL_STORY_RC51__.close(true);});
 await page.waitForFunction(()=>__HAPIL_COMBAT_AUDIO_V1__.allowsEffects());
 const sample=()=>page.evaluate(()=>{const s=__MONGSE_QA_STATE__;return{zone:s.zone,time:s.time,hp:s.hp,x:s.x,y:s.y,speed:s.rc127MovementSpeed};});const first=await sample();await page.keyboard.down('ArrowRight');await page.waitForTimeout(450);await page.keyboard.up('ArrowRight');await page.waitForTimeout(1500);const last=await sample();assert(last.time>first.time);assert(Math.abs(last.speed-6.471685)<1e-8);assert(Math.hypot(last.x-first.x,last.y-first.y)>.2);await page.screenshot({path:path.join(out,name+'-combat.png')});
 const decoded=await page.evaluate(async()=>{const audio=new AudioContext(),rows=[];try{for(const file of ['attack-wood','attack-melee','parry','hurt-neutral']){const response=await fetch('./audio/rc131/'+file+'.ogg');if(!response.ok)throw Error('Audio '+response.status);const buffer=await audio.decodeAudioData(await response.arrayBuffer());let peak=0;const data=buffer.getChannelData(0);for(const v of data)peak=Math.max(peak,Math.abs(v));rows.push({file,duration:buffer.duration,channels:buffer.numberOfChannels,peak});}}finally{await audio.close();}return rows;});assert(decoded.every(r=>r.duration>2.2&&r.duration<2.4&&r.peak>0&&r.peak<1));
 const before=await page.evaluate(()=>__RC131_MEDIA__.snapshot());const priority=await page.evaluate(()=>{const s=__MONGSE_QA_STATE__;__RC131_BRIDGE_REF__.current.stopEffects();const wood=__RC131_RESOLVER__('hwando','A'),melee=__RC131_RESOLVER__('slayer','A'),hurt=__HAPIL_AUDIO_RC130__.route(s,{channel:'ally-hurt',heroId:null},'old');__RC131_PLAY__(wood,.4);__RC131_PLAY__(melee,.4);__RC131_PLAY__(hurt,.44);return{wood,melee,hurt,media:__RC131_MEDIA__.snapshot()};});
 await page.waitForFunction(()=>__RC131_MEDIA__.events.some(e=>e.accepted&&e.src.includes('/hurt-neutral.ogg')));assert(priority.hurt.endsWith('hurt-neutral.ogg'));assert(priority.media.active<=2);await page.waitForTimeout(2600);
 await page.evaluate(()=>{__RC131_BRIDGE_REF__.current.stopEffects();const s=__MONGSE_QA_STATE__,p=__HAPIL_AUDIO_RC130__.route(s,{channel:'guard',contactResult:'PARRY'},'old');__RC131_PLAY__(p,.4);});await page.waitForFunction(()=>__RC131_MEDIA__.events.some(e=>e.accepted&&e.src.includes('/parry.ogg')));
 await page.evaluate(()=>__HAPIL_CONTROLS_V31329__.binding.setSettings(s=>({...s,sound:false})));await page.waitForFunction(()=>__RC131_MEDIA__.snapshot().active===0);const muted=await page.evaluate(()=>__RC131_MEDIA__.snapshot());await page.evaluate(()=>__RC131_PLAY__('./audio/rc131/attack-wood.ogg',1));await page.waitForTimeout(120);const afterMute=await page.evaluate(()=>__RC131_MEDIA__.snapshot());assert.equal(afterMute.events.length,muted.events.length,'muted cue cannot play');
 const final=await page.evaluate(()=>({audio:__RC131_MEDIA__.snapshot(),routing:__HAPIL_AUDIO_CUES_RC131__.snapshot()}));assert(final.audio.max<=2,'pending plus active uploaded voices bounded');assert.equal(final.routing.failedPaths.length,0);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 report.profiles.push({name,startup:{first,last,usedProgressCheats:false},decoded,priority,before,final,errors,failed,status:'passed'});save();console.log('RC131_BROWSER_PROFILE',JSON.stringify({name,status:'passed',decoded,peakOwnedVoices:final.audio.max,errors,failed}));await ctx.close();}
 report.status='passed';}catch(e){report.status='failed';report.error=String(e.stack||e);throw e;}finally{save();await browser?.close();server.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
