'use strict';
// Native staged fixtures. Every forced health/time/progress change is deliberate test setup.
// These are browser emulations; no full natural campaign or physical phone claim.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'..'),out=path.join(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results'),'rc133');fs.mkdirSync(out,{recursive:true});
const bridge=`\nwindow.__RC133_QA__={initial:oi,hero:id=>F.find(h=>h.id===id),get midbossTemplates(){return Object.entries(N).flatMap(([zone,z])=>(z.enemies??[]).filter(a=>a.midboss).map(a=>({zone,id:a.id})));},spawnMidbossWave(s){const a=ni(s.zone,'midboss');if(!a)return null;const twin=HAPIL_createMidbossDuoRC59(s,a,s.zone);s.enemies.push(a,...(twin?[twin]:[]));window.__HAPIL_RC69__?.completeMidbossWave(s);return a;},phase:(...a)=>MONGSE_enemyActivePhase(...a),wrathTick:(...a)=>MONGSE_tickSevenSinBossMechanics(...a),wrathSchedule:(...a)=>MONGSE_scheduleWrathBossSequence(...a),brain:(...a)=>MONGSE_tickBossCombatBrainSmartR1(...a),move:(...a)=>ft(...a),restoreEnemies:(...a)=>Ii(...a),blocked:ut,contains:Di,gap:(...a)=>MONGSE_tickBossGapCharge31226(...a),hitRadius:(...a)=>MONGSE_enemyHitRadius(...a),torso:(...a)=>MONGSE_enemyTorsoOffset(...a),recordProjectile:(...a)=>window.__HAPIL_CONTACT_V31336__?.recordProjectileBitmap(...a),midbossPresentation:(a,t)=>{const copy={...a,attackAt:t+1,attackImpactAt:t+.1,attackStarted:t};return {actual:MONGSE_midbossAttackPresentationV31237(copy,t).actorSprite,expected:MONGSE_phaseSprite(copy)??copy.actionSprites?.idle??copy.sprite};}};`;
const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.webp':'image/webp','.wav':'audio/wav','.mp3':'audio/mpeg','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(file.endsWith('/assets/index-v31526.js')?fs.readFileSync(file,'utf8')+bridge:fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:!!cp.execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),status:'running',scope:'Staged real channel/save/boss-death/render paths; desktop/phone browser emulation',profiles:[]};const save=()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));
try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const[name,width,height,mobile]of[['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1}),page=await context.newPage(),row={name,errors:[],missing:[],status:'running'};report.profiles.push(row);page.on('pageerror',e=>row.errors.push(e.stack||e.message));page.on('response',r=>{if(r.status()>=400)row.missing.push({url:r.url(),status:r.status()});});
 try{
 await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_RC133_NATIVE__?.installed);await page.waitForFunction(()=>window.__HAPIL_MEDIA_ART_RC133__?.ready,null,{timeout:30000});await page.evaluate(()=>{const B=window.__HAPIL_RC86_BRIDGE__,frame=B.renderFrame;B.renderFrame=function(...args){window.__RC133_FRAMES__=(window.__RC133_FRAMES__??0)+1;if(window.__RC133_FIXED_STATE__){args[1]=window.__RC133_FIXED_STATE__;args[3]=window.__RC133_QA__.hero(args[1].activeHeroId)||args[3];}return frame.apply(this,args);};});await page.keyboard.press('Escape');await page.evaluate(()=>window.__HAPIL_SAMONG_RC91__.unlock(null,'777'));await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();await page.locator('[data-game-mode-v31354="DREAM"]').click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__);for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
 row.native=await page.evaluate(()=>{
 const N=window.__HAPIL_RC133_NATIVE__,Q=window.__RC133_QA__,B=window.__HAPIL_RC86_BRIDGE__,U=window.__HAPIL_SAMONG_POLICY_RC133__,A=window.__HAPIL_SAMONG_RC91__,D=window.__HAPIL_CHANNEL_V31364__,H=window.__HAPIL_INNER_FINAL_RC133__,problems=[],details={};let checks=0;
 const test=(ok,label,extra)=>{checks++;if(!ok)problems.push({label,extra});},close=(a,b)=>Math.abs(a-b)<1e-6;
 const make=(zone='ep1b03',mode='DREAM')=>{const s=Q.initial();Object.assign(s,{zone,time:100,x:16,y:24,hp:240,maxHp:240,activeHeroId:'gunner',gameModeV31346:mode,samongUnlockedRC91:true,practiceV31329:false,awakeningUntil:0,encounterLockUntil31226:0,encounterWallUnlockAtV31227:0,encounterDialogue31226:null,timeStopUntil:0});return s;};
 const s=make();s.enemies=[B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03')];
 for(let i=1;i<=7;i++){s.time+=8;s.awakeningUntil=s.time;s.resonance=100;test(D.convert(s,s),'real normal EGO channel conversion '+i);test(U.status(s).count===(i===7?0:i),'counter consumes exactly on seventh '+i);}
 test(A.active(s)&&s.samongPassiveRC91.origin==='ego','seventh EGO activated live RC91');test(close(s.samongPassiveRC91.active,7)&&close(s.samongPassiveRC91.cooldown,77),'default 7/77');test(s.hp===240,'EGO activation does not heal');test(!A.tryRevive(s)&&!A.tryEgo(s),'same tick activation not duplicated');
 const reservation=make();reservation.enemies=s.enemies;A.tryEgo(reservation);reservation.samongPassiveRC91.cooldown=2;
 for(let i=0;i<7;i++){reservation.time+=8;reservation.awakeningUntil=reservation.time;reservation.resonance=100;D.convert(reservation,reservation);}
 test(U.status(reservation).count===7&&U.status(reservation).pending&&!A.active(reservation),'cooldown reserves seventh entry');
 const p={samongDuration:2,samongCooldown:3,samongPower:3,samongProtection:2,samongResonance:3};reservation.samongUpgradesRC133=p;const raw=N.save(reservation,'gunner',[],p,4),normal=N.normalize(raw);test(!!normal,'native save validates');test(normal?.samongRC91?.egoRC133?.pending===true,'reserved counter saved');test(normal?.passives?.samongDuration===2,'native save retains upgrade keys');
 const loaded=make();loaded.enemies=Q.restoreEnemies(normal);B.restoreEntry(loaded,normal);test(U.status(loaded).pending&&U.status(loaded).count===7,'native restore retains seventh reservation');test(loaded.samongUpgradesRC133.samongDuration===2,'native restore upgrade levels');A.advance(loaded,2.1,false);test(A.active(loaded)&&close(loaded.samongPassiveRC91.duration,9)&&close(loaded.samongPassiveRC91.cooldown,65.45),'reservation resumes after actual countdown with bounded upgrades');
 const lethal=make();lethal.enemies=s.enemies;lethal.hp=0;Object.assign(U.memory(lethal),{count:7,pending:true});test(A.tryRevive(lethal),'lethal boundary uses revival');test(U.status(lethal).count===0&&!A.tryEgo(lethal)&&lethal.samongPassiveRC91.activations===1,'lethal/seventh boundary atomic');
 const newRun=make();test(U.status(newRun).count===0,'new state clears run counter');
 const mid=[];for(const mode of ['STORY','DREAM'])for(const row of Q.midbossTemplates.filter(row=>row.zone!=='ep1a07')){
  const a=make(row.zone,mode);N.enter(a,row.zone,false);a.time=100;a.encounterLockUntil31226=0;a.encounterDialogue31226=null;
  let delayed=false;if(!a.enemies.some(e=>e.midboss)){a.enemies=[];delayed=true;Q.spawnMidbossWave(a);}N.midpoint(a);A.scaleEnemies(a);
  const leaders=a.enemies.filter(e=>e.midboss&&e.hp>0),entry={mode,zone:row.zone,delayed,count:leaders.length,actors:leaders.map(e=>({id:e.id,sprite:e.sprite,maxHp:e.maxHp}))};mid.push(entry);
  test(leaders.length===(mode==='DREAM'?3:2),'native initial/delayed midboss count '+mode+' '+row.zone,entry);
  const authored=N.authoredMidboss(row.zone,leaders[0]);
  test(leaders.every(e=>e.sprite===authored.sprite&&e.rc135FissionIdentity===authored.id&&e.rc133TemplateId===authored.id&&e.combatOwnerIdRC69===authored.id),'map-authored same-identity fission '+mode+' '+row.zone,{...entry,expected:authored.id,sprite:authored.sprite});
  test(new Set(leaders.map(e=>e.id)).size===leaders.length,'independent fission entity IDs '+mode+' '+row.zone,entry);
  const initialVisuals=leaders.filter(a=>a.rc133VisualTemplate).map(a=>Q.midbossPresentation(a,100));test(initialVisuals.every(a=>a.actual===a.expected),'chosen visual remains the attack body '+mode+' '+row.zone,initialVisuals);
  const survivor=leaders.at(-1);leaders[0].hp=0;a.enemies=a.enemies.filter(e=>e!==leaders[0]);N.midpoint(a);
  test(a.enemies.filter(e=>e.midboss).length===leaders.length-1,'death does not refill '+mode+' '+row.zone);
  const saved=N.normalize(N.save(a,'gunner',[],{},0)),loaded=make(row.zone,mode);loaded.enemies=Q.restoreEnemies(saved);B.restoreEntry(loaded,saved);A.scaleEnemies(loaded);
  test(loaded.enemies.filter(e=>e.midboss&&e.hp>0).length===leaders.length-1,'native load retains surviving count '+mode+' '+row.zone,{actors:loaded.enemies.filter(e=>e.midboss).map(e=>e.id),saved:saved?.midbossEncounterRC133});
  test(close(loaded.enemies.find(e=>e.id===survivor.id)?.maxHp,survivor.maxHp),'midboss HP not multiplied on load '+mode+' '+row.zone,{before:survivor.maxHp,after:loaded.enemies.find(e=>e.id===survivor.id)?.maxHp});
  const restoredVisuals=loaded.enemies.filter(a=>a.rc133VisualTemplate).map(a=>Q.midbossPresentation(a,100));test(restoredVisuals.every(a=>a.actual===a.expected),'restored chosen visual remains the attack body '+mode+' '+row.zone,restoredVisuals);
  test(N.foundation(a).regions.includes(row.zone),'visited region foundation '+mode+' '+row.zone);
 }
 details.midboss=mid;const legacy=make('ep1a07','STORY'),legacySave=N.normalize(N.save(legacy,'gunner',[],{},0));test(legacySave.zone==='ep1a08','removed ep1a07 save migrates to actual hospital route');
 const w=make('ep1b03','STORY'),a=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03');Object.assign(a,{x:w.x+.8,y:w.y,attackAt:0,recoverUntil:0,phaseTransitionUntil:0,atomicCastUntil31210:0,combatEntryGraceUntilV31239:0,staggerUntil:0});w.enemies=[a];const dest=N.destination(w,a);test(!!dest&&N.safeDestination(w,a,dest),'warp has native valid distant destination',dest);if(dest){w.pendingHits=[{id:999,shape:'circle',x:dest.x,y:dest.y,radius:2,damage:10,at:w.time+2}];test(!N.safeDestination(w,a,dest),'warp rejects actual pending area');w.pendingHits=[];N.warp(w,a);test(!!a.rc133Warp,'close player schedules warp');const b=B.cloneEnemy(a,'ep1b03');b.id='warp-second-fixture';b.x=w.x-.8;w.enemies.push(b);N.warp(w,b);test(!b.rc133Warp,'shared cooldown prevents simultaneous warp');w.time+=.56;N.warp(w,a);test(!a.rc133Warp&&Math.hypot(a.x-w.x,a.y-w.y)>=8,'warp safely commits');a.gapChargeV31226={phase:'dash'};w.pendingHits=[{sourceId:a.id,gapChargeV31226:true},{sourceId:a.id,id:'noncharge'}];Q.gap(w,a,0);test(!a.gapChargeV31226&&w.pendingHits.length===1&&w.pendingHits[0].id==='noncharge','boss gap charge cleared without cancelling noncharge');}
 const reserved=make('ep1b03','STORY'),r1=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03'),r2=B.cloneEnemy(r1,'ep1b03');r2.id='second-warp-rc133';for(const [i,a]of [r1,r2].entries())Object.assign(a,{x:reserved.x+(i?-.8:.8),y:reserved.y,attackAt:0,recoverUntil:0,phaseTransitionUntil:0,atomicCastUntil31210:0,staggerUntil:0});reserved.enemies=[r1,r2];N.warp(reserved,r1);test(!!r1.rc133Warp,'shared warp lease admitted');r1.atomicCastUntil31210=reserved.time+5;reserved.time+=2;N.warp(reserved,r1);N.warp(reserved,r2);test(!!r1.rc133Warp&&!r2.rc133Warp,'deferred cast keeps shared warp reservation beyond nominal timer');r1.hp=0;N.warp(reserved,r2);test(!!r2.rc133Warp,'dead owner releases shared reservation');
 const V=window.__HAPIL_BOSS_V31315__,charges=[];
 for(const {actor:template,zone}of V.rankedRows()){if(!V.profile(template,zone))continue;const st=make(zone,'STORY'),actor=B.cloneEnemy(template,zone);Object.assign(actor,{x:8,y:8,hp:100,staggerUntil:0,phaseTransitionUntil:0,dynamicBossReadyAtV31315:0});st.enemies=[actor];
  const result=V.enqueue(st,actor,'dash');test(result&&result.hit.dynamicBossModeV31315!=='dash','dynamic request converted to stationary coverage '+actor.id);
  const x=actor.x,y=actor.y;V.onImpact(st,{...result.hit,dynamicBossModeV31315:'dash'});st.time+=1;V.tick(st);test(actor.x===x&&actor.y===y&&V.activeDashes(st)===0,'legacy dynamic impact cannot move '+actor.id);charges.push(actor.id);
 }
 details.stationaryDynamicPatterns=charges;
 const wrath=make('ep1b07','STORY'),wa=B.cloneEnemy(B.actor('ep1b07','b07-boss'),'ep1b07');wa.x=8;wa.y=8;wrath.enemies=[wa];const wx=wa.x,wy=wa.y;
 const ignition=Q.wrathSchedule(wrath,wa,Q.phase(wa),wrath.time+.4,{sevenSinMechanic:'wrath-ignite',telekineticRain:true});test(!!ignition&&wrath.pendingHits.includes(ignition),'wrath preserves committed nonmoving ignition line');wrath.time=wa.wrathDashAt+.01;Q.wrathTick(wrath);test(wa.x===wx&&wa.y===wy&&wa.wrathRageUntil>wrath.time,'wrath ignition/rage cadence without self charge');
 for(const flags of [{episodeCosmicFinalV387:true},{dreamCosmicTrialV31346:2},{rc133InnerBoss:true}]){const st=make(),actor=B.cloneEnemy(B.actor('ep1b03','b03-boss'),'ep1b03');Object.assign(actor,flags,{x:8,y:8});st.enemies=[actor];N.pin(actor);actor.x=9;actor.y=9;const result=Q.brain(st,actor,.1);window.__HAPIL_STAND_V31335__.tick(st,.1);Q.move(st.zone,actor,{x:12,y:12});N.warp(st,actor);test(actor.x===8&&actor.y===8&&!actor.rc133Warp&&result.moveScale===0,'cosmic/persona stationary core '+JSON.stringify(flags));}
 const humanoid=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');const body=[];for(let phase=0;phase<=3;phase++){humanoid.fixedPhase=phase;humanoid.currentPhase=phase;body.push({phase,radius:Q.hitRadius(humanoid),torso:Q.torso(humanoid).y,profile:window.__HAPIL_STAND_V31335__.profile(humanoid)});}test(body.every(row=>row.radius===.72&&row.torso===-122*.62&&row.profile?.human===body[0].profile?.human),'humanoid core same target/radius through Stand phases',body.map(({phase,radius})=>({phase,radius})));details.humanoid=body.map(({phase,radius})=>({phase,radius}));
 // Source-owned Story awakenings use real native decks; all progress/HP here is staged setup.
 const C=window.__HAPIL_EPISODE_COSMIC_V387__,cosmic=[];
 for(const spec of C.episodes){const st=make(spec.zone,'STORY'),dead=B.cloneEnemy(B.actor(spec.zone,spec.triggerId),spec.zone);dead.hp=0;st.enemies=[dead];C.beforeDeath(st,dead);st.enemies=[];
  test(C.startFinal(st,spec.zone),'native Story source awakening starts '+spec.triggerId);const a=st.enemies.find(e=>e.episodeCosmicFinalV387);
  test(a?.id===spec.triggerId&&a.sprite===spec.pose&&a.sourceBossId===spec.triggerId,'actual source identity and awakening pixels '+spec.triggerId);
  test(B.zoneCombatCleared(st,spec.zone)===false,'living source awakening keeps native exit locked '+spec.triggerId);
  st.time=a.episodeCosmicSignatureAtV387+.01;C.tick(st);test(a.episodeCosmicFirstSignatureDispatchedV387&&a.episodeCosmicSignatureCountV387>0,'actual native source signature dispatch '+spec.triggerId,{name:a.episodeCosmicSignatureNameV387,count:a.episodeCosmicSignatureCountV387});
  N.pin(a);const x=a.x,y=a.y;Q.brain(st,a,.1);Q.move(st.zone,a,{x:x+1,y:y+1});N.warp(st,a);test(a.x===x&&a.y===y&&!a.rc133Warp,'source awakening remains stationary '+spec.triggerId);
  const raw=N.save(st,'gunner',[],{},0);raw.episodeCosmicFinalV387.cosmicId=spec.legacyCosmicId;const normal=N.normalize(raw),loaded=make(spec.zone,'STORY');loaded.enemies=Q.restoreEnemies(normal);B.restoreEntry(loaded,normal);const restored=loaded.enemies.find(e=>e.episodeCosmicFinalV387);
  test(restored?.id===spec.triggerId&&restored.sprite===spec.pose&&close(restored.hp,a.hp)&&loaded.enemies.filter(e=>e.episodeCosmicFinalV387).length===1,'legacy Kair alias restores exactly one source awakening '+spec.triggerId);
  const dream=make(spec.zone,'DREAM'),source=B.cloneEnemy(B.actor(spec.zone,spec.triggerId),spec.zone);source.hp=0;dream.enemies=[source];C.beforeDeath(dream,source);test(!dream.hapilEpisodeCosmicV387,'source Story awakening remains isolated from Dream '+spec.triggerId);
  cosmic.push({id:a.id,sprite:a.sprite,signature:a.episodeCosmicSignatureNameV387,count:a.episodeCosmicSignatureCountV387,legacy:spec.legacyCosmicId});
 }
 test(new Set(cosmic.map(e=>e.sprite)).size===6,'six distinct source awakening images');details.sourceCosmic=cosmic;
 const h=make('cult04'),leader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');leader.hp=0;h.enemies=[leader];test(H.beforeDeath(h,leader),'actual cult leader id admits hidden route');test(h.innerFinalRC133?.phase==='reveal'&&!!H.boss(h),'hidden live actor created');const bound=H.growth(h,{infinitePower:1e100,samongDuration:9999});test(bound<=2.1,'inner persona growth bounded');const hs=N.save(h,'gunner',[],{},0),hn=N.normalize(hs),hr=make('cult04');hr.enemies=Q.restoreEnemies(hn);B.restoreEntry(hr,hn);test(H.active(hr)&&hr.enemies.filter(e=>e.id===H.id).length===1,'hidden native save/restore one actor');
 h.innerFinalRC133.intro=0;h.innerFinalRC133.shotDelay=0;H.tick(h,.016);const shots=h.hostileProjectiles.filter(e=>e.rc133InnerShot);test(shots.length===6,'gunner traits create bounded six shots');test(shots.every(q=>Math.abs(Math.hypot(q.vx,q.vy)-3.6)<1e-6&&q.radius<=.32&&q.collisionDisabledUntil31219>=h.time+.65),'inner shots native windup and bounded speed');
 const innerTraits=[];for(const hero of A.heroes){const st=make('cult04'),dead=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');st.activeHeroId=hero;dead.hp=0;st.enemies=[dead];H.start(st,dead);st.innerFinalRC133.intro=0;st.innerFinalRC133.shotDelay=0;H.tick(st,.016);const shots=st.hostileProjectiles.filter(q=>q.rc133InnerShot);innerTraits.push({hero,count:shots.length,speed:Math.hypot(shots[0]?.vx,shots[0]?.vy),color:shots[0]?.color});test(shots.length===H.traits[hero].count&&shots.every(q=>q.damage<=20&&q.radius<=.32&&Math.hypot(q.vx,q.vy)<=4.8),'hero persona borrows bounded native trait '+hero,innerTraits.at(-1));
  const previous=st.innerFinalRC133.cycle;st.hostileProjectiles.push(...Array.from({length:72-shots.length},()=>({})));st.innerFinalRC133.shotDelay=0;H.tick(st,.016);test(st.hostileProjectiles.length===72&&st.innerFinalRC133.cycle===previous,'persona atomic projectile cap '+hero);
  const pending=st.innerFinalRC133.awakeningCooldown;st.timeStopUntil=st.time+10;H.tick(st,.1);test(st.innerFinalRC133.awakeningCooldown===pending,'persona timers pause during time stop '+hero);
 }
 details.innerTraits=innerTraits;test(new Set(innerTraits.map(row=>JSON.stringify([row.count,row.speed,row.color]))).size===8,'eight distinct hero trait profiles');
 const duel=make('cult04'),duelLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');duelLeader.hp=0;duel.enemies=[duelLeader];H.start(duel,duelLeader);duel.innerFinalRC133.intro=0;const duelBoss=H.boss(duel);duelBoss.hp=Math.ceil(duelBoss.maxHp*.1);duel.hp=0;
 test(A.tryRevive(duel),'paired awakening intercepts the real Samong lethal-revive path');test(duel.hp===Math.ceil(duel.maxHp*.22)&&duelBoss.hp===Math.ceil(duelBoss.maxHp*.1),'paired awakening revives lethal player and preserves living boss health',{player:[duel.hp,duel.maxHp],boss:[duelBoss.hp,duelBoss.maxHp]});test(A.active(duel)&&duel.innerFinalRC133.awake===7&&H.mood(duel)==='opposition','both awaken into the readable split duel');test(duel.samongPassiveRC91.encounterRC128.used,'paired duel consumes the ordinary encounter-revival token');
 const duelCanvas=document.createElement('canvas');duelCanvas.width=200;duelCanvas.height=100;const duelCtx=duelCanvas.getContext('2d');duelCtx.fillStyle='#5299cc';duelCtx.fillRect(0,0,200,100);H.compose(duelCtx,duel,duelCanvas);const duelLeft=Array.from(duelCtx.getImageData(40,50,1,1).data),duelRight=Array.from(duelCtx.getImageData(160,50,1,1).data);test(duelLeft[0]===duelLeft[1]&&duelRight[0]>duelRight[1]&&duelCtx.filter==='none','live clash renders opposing halves and restores canvas state',{duelLeft,duelRight,filter:duelCtx.filter});
 const duelSave=N.normalize(N.save(duel,'gunner',[],{},0)),duelRestore=make('cult04');duelRestore.enemies=Q.restoreEnemies(duelSave);B.restoreEntry(duelRestore,duelSave);test(duelRestore.innerFinalRC133?.clash?.used===true&&A.active(duelRestore)&&H.mood(duelRestore)==='opposition','native save/load retains one-use duel and both awakenings');duelRestore.hp=0;duelRestore.samongPassiveRC91.active=0;duelRestore.samongPassiveRC91.cooldown=0;test(!A.tryRevive(duelRestore),'saved paired token cannot trigger a second revival');
 const completed=make('cult04'),doneLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');doneLeader.hp=0;completed.enemies=[doneLeader];H.start(completed,doneLeader);const inner=H.boss(completed);completed.pendingHits.push({sourceId:H.id,damage:10});completed.hostileProjectiles.push({sourceId:H.id,damage:10});const liveHp=completed.hp;inner.hp=0;test(H.beforeDeath(completed,inner),'native boss-first lethal intercepts boss removal');test(inner.hp===Math.ceil(inner.maxHp*.22)&&completed.hp===liveHp&&completed.innerFinalRC133.clash.reason==='boss'&&H.mood(completed)==='opposition','native boss-first revives only dead boss and counter awakens healthy player');const bossFirstSave=N.normalize(N.save(completed,'gunner',[],{},0)),bossFirstRestore=make('cult04');bossFirstRestore.enemies=Q.restoreEnemies(bossFirstSave);B.restoreEntry(bossFirstRestore,bossFirstSave);test(bossFirstRestore.innerFinalRC133.clash.used&&bossFirstRestore.innerFinalRC133.clash.reason==='boss'&&bossFirstRestore.hp===liveHp&&H.mood(bossFirstRestore)==='opposition','native boss-first save/load retains both awakened states and living HP');inner.hp=0;H.beforeDeath(completed,inner);test(completed.innerFinalRC133.phase==='complete'&&completed.pendingHits.length===0&&completed.hostileProjectiles.length===0,'inner death cleans actual owned attacks');const completeSave=N.normalize(N.save(completed,'gunner',[],{},0)),resumed=make('cult04');resumed.enemies=Q.restoreEnemies(completeSave);B.restoreEntry(resumed,completeSave);test(resumed.bossDefeated&&!H.boss(resumed)&&H.mood(resumed)==='normal','completed save cannot resurrect inner boss');
 for(const mode of ['DREAM','STORY']){const village=make('village',mode);village.enemies=[{id:'unrelated',hp:10}];village.bossDefeated=false;B.restoreEntry(village,{...completeSave,zone:'village',gameModeV31346:mode});test(village.innerFinalRC133?.phase==='complete'&&!H.boss(village)&&H.mood(village)==='normal','completed history survives village restore without a filter '+mode);test(village.enemies.some(a=>a.id==='unrelated')&&!village.bossDefeated,'completed history does not alter another map encounter '+mode);}

 const storyLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04'),story=make('cult04','STORY');storyLeader.hp=0;test(!H.beforeDeath(story,storyLeader)&&!story.innerFinalRC133,'Story cult leader route preserved');
 const moods=[];for(const [player,boss,expected]of[[false,false,'normal'],[true,false,'player'],[false,true,'boss'],[true,true,'opposition']]){h.samongPassiveRC91={active:player?7:0,cooldown:77,duration:7,heroId:'gunner'};h.innerFinalRC133.awake=boss?7:0;test(H.mood(h)===expected,'four-state mood '+expected);moods.push(expected);}details.moods=moods;
 h.hp=0;test(H.mood(h)==='normal','death clears composition eligibility');h.hp=240;h.innerFinalRC133.phase='complete';test(H.mood(h)==='normal','completion clears composition eligibility');h.zone='ep1b03';test(H.mood(h)==='normal','other zone composition normal');
 // Deterministic draw surfaces isolate the compositor and prove context restoration.
 const pixel=[];for(const [p,b,expected]of[[false,false,'normal'],[true,false,'player'],[false,true,'boss'],[true,true,'opposition']]){h.zone='cult04';h.innerFinalRC133.phase='fight';h.innerFinalRC133.awake=b?7:0;h.samongPassiveRC91.active=p?7:0;const c=document.createElement('canvas');c.width=200;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#5299cc';ctx.fillRect(0,0,200,100);ctx.filter='none';H.compose(ctx,h,c);const left=Array.from(ctx.getImageData(40,50,1,1).data),right=Array.from(ctx.getImageData(160,50,1,1).data);test(ctx.filter==='none'&&ctx.globalCompositeOperation==='source-over','compositor no filter leak '+expected);if(expected==='player')test(left[0]===left[1]&&left[1]===left[2],'whole player grayscale');if(expected==='boss')test(left[0]>left[1]&&left[0]>left[2],'whole boss red');if(expected==='opposition')test(left[0]===left[1]&&right[0]>right[1],'opposed halves');pixel.push({expected,left,right});}details.pixel=pixel;
 // Verified uploaded pixels are decoded and wired before the compatibility fixture below.
 const M=window.__HAPIL_MEDIA_ART_RC133__,sourceArt=[];
 test(M.ready&&M.diagnostics().failed.length===0,'all actual uploaded art frames decoded',M.diagnostics());
 const actual=make('cult04'),actualLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');actualLeader.hp=0;actual.enemies=[actualLeader];H.start(actual,actualLeader);
 test(H.map(actual,'fallback')===M.paths.reveal,'uploaded concept reveal map');actual.innerFinalRC133.intro=0;H.tick(actual,.016);test(H.map(actual,'fallback')===M.paths.map,'uploaded playable arena selected after reveal');
 const actualBoss=H.boss(actual);
 for(let i=0;i<8;i++){const angle=Math.PI/2+i*Math.PI/4,dx=Math.cos(angle),dy=Math.sin(angle);const pose={...actual,x:actualBoss.x+dx*.5+dy,y:actualBoss.y+dy-dx*.5};
  actual.innerFinalRC133.awake=0;test(H.frame(pose,actualBoss)===M.frames[i],'base source direction '+i);
  actual.innerFinalRC133.awake=7;test(H.frame(pose,actualBoss)===M.awakeFrames[i],'awake source direction '+i);sourceArt.push({direction:i,base:M.frames[i],awake:M.awakeFrames[i]});}
 actual.innerFinalRC133.shotDelay=0;actual.hostileProjectiles=[];H.tick(actual,.016);test(actual.hostileProjectiles.every(q=>q.sprite===M.personaTraitSkills.gunner),'gunner source orb uses native collision descriptor');
 const sourceSave=N.normalize(N.save(actual,'gunner',[],{},0)),sourceRestored=make('cult04');sourceRestored.enemies=Q.restoreEnemies(sourceSave);B.restoreEntry(sourceRestored,sourceSave);test(H.boss(sourceRestored)?.sprite?.includes('/awake-'),'uploaded awakening native save restore');
 const ordinary=[];for(let i=1;i<=10;i++){const zone='kair'+String(i).padStart(2,'0'),path=B.projectileSprite({id:'ordinary-source-fixture',boss:false,midboss:false},zone);ordinary.push(path);test(M.chrono.includes(path),'authored Chrono ordinary atlas '+zone);}
 test(new Set(ordinary).size>=8,'Kair ordinary projectiles use distinct actual shapes',ordinary);
 test(B.projectileSprite({id:'ep1a08-ordinary-fixture'},'ep1a08').includes('hospital_syringe'),'hospital generic art resolver aligned');
 // New hidden duel requirements: full-health first lethal admission and all nine real skills.
 const first=make('cult04'),firstLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');firstLeader.hp=0;first.enemies=[firstLeader];H.start(first,firstLeader);const firstBoss=H.boss(first),beforeBoss=firstBoss.hp;
 test(firstBoss.maxHp>=firstLeader.maxHp*1.65&&firstBoss.maxHp<=3000000,'hidden strength exceeds source leader with bounded maximum',{leader:firstLeader.maxHp,hidden:firstBoss.maxHp});
 Object.assign(U.memory(first),{count:7,pending:true});first.hp=0;test(A.tryRevive(first),'very first lethal contact triggers at full hidden boss HP');test(firstBoss.hp===beforeBoss,'first lethal contact cannot erase boss progress');test(first.innerFinalRC133.clash.admitted&&U.status(first).count===0&&!U.status(first).pending,'first lethal clash atomically consumes EGO7 pending token');
 const skills=[];for(let i=0;i<H.deck.length;i++){const skillState=make('cult04'),dead=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');dead.hp=0;skillState.enemies=[dead];H.start(skillState,dead);Object.assign(skillState.innerFinalRC133,{intro:0,cycle:i,shotDelay:0});H.tick(skillState,.016);const packets=[...skillState.hostileProjectiles,...skillState.pendingHits].filter(q=>q.rc133Skill===H.deck[i].key);test(packets.length>0,'actual native skill dispatch '+H.deck[i].key);test(packets.every(q=>q.damage>0&&q.damage<=20&&q.sourceId===H.id),'actual skill packet bounded '+H.deck[i].key);test(packets.every(q=>(q.sprite??q.sevenSinImpactSprite)===M.personaSkills[H.deck[i].key]),'actual uploaded skill image '+H.deck[i].key);skills.push({key:H.deck[i].key,count:packets.length,shape:packets[0]?.shape??'bullet',sprite:packets[0]?.sprite??packets[0]?.sevenSinImpactSprite});}
 details.hiddenNew={firstLethalAtFullHealth:true,bossHealth:beforeBoss,skills};
 details.uploadedArt={decoded:M.diagnostics(),sourceArt,concept:M.paths.reveal,arena:M.paths.map,trait:M.personaTraitSkills.gunner,save:true,chronoOrdinary:ordinary};
 // RC134 native actor ownership: unrelated modes/cosmic stationary rules above
 // remain tested. Here the actual native movement resolver is bound to each
 // staged hidden state and the native brain may not undo mirror tracking.
 const P=window.__HAPIL_PERSONA_DUEL_RC134__,control=window.__HAPIL_CONTROLS_V31329__,oldLive=control.binding.state.current,mirror=[];
 try{for(const hero of A.heroes){const st=make('cult04'),leader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');st.activeHeroId=hero;leader.hp=0;st.enemies=[leader];H.start(st,leader);control.binding.state.current=st;const actor=H.boss(st);
  test(P.contains(st,'left')&&P.contains(actor,'right'),'native spawn half ownership '+hero);const destination=Q.move(st.zone,st,{x:30,y:-30});st.x=destination.x;st.y=destination.y;test(P.contains(st,'left')&&!Q.blocked(st.zone,st.x,st.y,.8),'native walking resolves to valid left floor '+hero);
  st.x=30;st.y=2;test(P.contains(st,'left'),'native blink/knockback setters cannot cross '+hero);actor.x=2;actor.y=30;test(P.contains(actor,'right'),'native boss setters cannot cross '+hero);
  for(let i=0;i<180;i++)P.tick(st,.016);const before={x:actor.x,y:actor.y};N.pin(actor,st);Q.brain(st,actor,.016);window.__HAPIL_STAND_V31335__.tick(st,.016);test(close(actor.x,before.x)&&close(actor.y,before.y)&&!actor.rc133Anchor&&!actor.rc133Warp,'native brain/Stand retain controlled mirror '+hero);
  test(close(actor.x,st.y)&&close(actor.y,st.x),'native mirror reflection converges '+hero);mirror.push({hero,player:{x:st.x,y:st.y},boss:before});
 }}finally{control.binding.state.current=oldLive;}details.mirror=mirror;
 const sourcePackets=[];for(const [key,path]of Object.entries(M.personaSkills)){const q={id:actual.fxSerial++,sourceId:H.id,boss:true,kind:'projectile',born:actual.time,x:actual.x,y:actual.y,previousX:actual.x,previousY:actual.y,vx:-3,vy:3,radius:.24,sprite:path,fallbackSprite:path,spriteHeading:0,screenAligned31222:!['eye','lance'].includes(key)};const plan=window.__HAPIL_BITMAP_NATIVE_RC133__.projectile(actual,q);test(!!plan&&plan.path.includes('/rc134/persona-skills/'),'actual final bitmap uses only new source path '+key,plan);sourcePackets.push({key,path:plan?.path,area:plan?.area});}details.personaBitmap=sourcePackets;
 test(!window.__HAPIL_PORTRAIT_SPLIT_RC108__.shouldRender(document.querySelector('.game-stage canvas'),actual),'fixed native hidden camera owns one left/right view');const fixed=window.__HAPIL_VIEWPORT_RC104__.camera(actual);test(fixed.personaMirrorRC134&&close(fixed.x+640*fixed.scale,640),'native camera centers the mirror axis');
 // Staged art registry uses already shipped hero sprites, never uploaded source art.
 // Exercise the actual awakening transition and save reconstruction without
 // changing health, collision or the fallback used before source registration.
 const shipped=window.__HAPIL_RC95_NATIVE__.heroes,bodyArt=shipped[0].sprite,awakeArt=shipped[1].sprite;
 test(H.configure({ready:true,map:bodyArt,body:bodyArt,awakening:awakeArt,skills:[bodyArt]}),'staged existing art registry admitted');
 const artState=make('cult04'),artLeader=B.cloneEnemy(B.actor('cult04','c104-boss'),'cult04');artLeader.hp=0;artState.enemies=[artLeader];H.start(artState,artLeader);artState.innerFinalRC133.intro=0;artState.innerFinalRC133.awakeningCooldown=0;H.tick(artState,.016);
 test(H.boss(artState).sprite===awakeArt&&artState.innerFinalRC133.awake>0,'registered boss awakening art selected on actual timer transition');
 const artSave=N.normalize(N.save(artState,'gunner',[],{},0)),artRestore=make('cult04');artRestore.enemies=Q.restoreEnemies(artSave);B.restoreEntry(artRestore,artSave);
 test(H.boss(artRestore).sprite===awakeArt,'active boss awakening art restored with native save');
 artState.innerFinalRC133.awake=.01;H.tick(artState,.016);test(H.boss(artState).sprite===bodyArt&&artState.innerFinalRC133.awake===0,'registered body art returns when boss awakening expires');
 details.registeredArt={stagedShippedSprites:true,uploadedSourceArt:false,awakeningTransition:true,nativeSaveRestore:true,expiry:true};
 test(H.configure({ready:true,...M.paths,frames:M.frames,awakeFrames:M.awakeFrames,skills:Object.values(M.personaSkills),skillMap:M.personaSkills,traitSkills:M.personaTraitSkills}),'restore actual uploaded registry after compatibility fixture');
 actual.x=16;actual.y=24;actual.time+=3;actual.hostileProjectiles=[];actual.effects=[];actual.floatTexts=[];actual.innerFinalRC133.shotDelay=10;window.__RC133_FIXTURES__={hidden:actual,ego:s};return {checks,problems,details};
 });assert.deepEqual(row.native.problems,[]);
 // Staged resource pickup, then the ordinary React settings/growth UI.
 await page.evaluate(()=>{const b=window.__HAPIL_CONTROLS_V31329__.binding,s=b.state.current;b.actions.dismiss();s.egoDrops.push({id:s.fxSerial++,x:s.x,y:s.y,born:s.time,amount:3});});await page.waitForFunction(()=>window.__HAPIL_CONTROLS_V31329__.binding.shards.current>=3);await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.actions.settings());await page.getByRole('button',{name:'공명 강화',exact:true}).click();assert.equal(await page.locator('[data-upgrade-category="samongUpgrade"]:visible').count(),1);assert.equal(await page.locator('[data-samong-upgrade]').count(),5);const before=await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.shards.current);await page.locator('[data-samong-upgrade="samongDuration"]').click();await page.waitForFunction(()=>window.__HAPIL_CONTROLS_V31329__.binding.passives.current.samongDuration===1);assert.equal(await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.shards.current),before-1);row.upgradeUI={ordinaryReactPanel:true,stagedResourcePickup:true,tracks:5,purchased:'samongDuration',cost:1};await page.evaluate(()=>{const b=window.__HAPIL_CONTROLS_V31329__.binding;b.actions.dismiss();window.__HAPIL_MODES_V31346__.set('STORY',b.state.current);});await page.waitForTimeout(200);for(let i=0;i<16&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.binding.actions.settings());await page.getByRole('button',{name:'공명 강화',exact:true}).click();assert.equal(await page.locator('[data-upgrade-category="samongUpgrade"]').count(),0);row.upgradeUI.storyHidden=true;await page.evaluate(()=>{const b=window.__HAPIL_CONTROLS_V31329__.binding;b.actions.dismiss();window.__HAPIL_MODES_V31346__.set('DREAM',b.state.current);});
 // Native death closure for each staged source-owned Story finale; no natural campaign claim.
 row.liveCosmic=await page.evaluate(()=>{const B=window.__HAPIL_RC86_BRIDGE__,C=window.__HAPIL_EPISODE_COSMIC_V387__,mode=window.__HAPIL_MODES_V31346__,s=window.__MONGSE_QA_STATE__,rows=[];mode.set('STORY',s);
  for(const spec of C.episodes){window.__MONGSE_QA_API__.stageV3128BossShowcase(spec.zone);s.hapilEpisodeCosmicV387=null;const dead=B.cloneEnemy(B.actor(spec.zone,spec.triggerId),spec.zone);dead.hp=0;s.enemies=[dead];C.beforeDeath(s,dead);s.enemies=[];const started=C.startFinal(s,spec.zone),id=s.enemies.find(a=>a.episodeCosmicFinalV387)?.id,death=window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();rows.push({zone:spec.zone,id,started,death,complete:C.snapshot(s)?.status==='complete',remaining:s.enemies.filter(a=>a.episodeCosmicFinalV387).length});}
  mode.set('DREAM',s);return rows;});for(const final of row.liveCosmic){assert(final.started&&final.death.pass&&final.complete&&final.remaining===0,'actual source awakening death must close exactly once: '+JSON.stringify(final));}
 // Exercise the installed live React enemy-death closure; the QA handler explicitly forces boss HP=0.
 row.liveHidden=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;window.__MONGSE_QA_API__.stageV3128BossShowcase('cult04');s.innerFinalRC133=null;const dead=window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();return{dead,phase:s.innerFinalRC133?.phase,id:window.__HAPIL_INNER_FINAL_RC133__.boss(s)?.id};});assert.equal(row.liveHidden.phase,'reveal','live native cult death enters hidden phase');assert.equal(row.liveHidden.id,'inner-evil-rc133');
 // Full gameplay frames run RC95 calibration before Dream scaling. Do not
 // substitute a direct H.tick fixture for this bounded-health regression.
 // RC25 has an independent RAF clock. Flush that native clock at both
 // observations so one pending frame cannot be charged to the wrong interval.
 // Keep the exact native regeneration bound; no extra tolerance is admitted.
 const liveHealth=()=>page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__,H=window.__HAPIL_INNER_FINAL_RC133__;window.__HAPIL_RAID_RC24__.tick(s);const a=H.boss(s);return{frames:window.__RC133_FRAMES__,time:s.time,hp:a?.hp,maxHp:a?.maxHp,modelMax:s.innerFinalRC133?.maxHp,snapshot:H.snapshot(s)};});
 row.liveHealth={entry:await liveHealth()};await page.waitForTimeout(400);row.liveHealth.afterFrames=await liveHealth();
 assert(row.liveHealth.afterFrames.frames>row.liveHealth.entry.frames,'hidden regression must run live frames');
 assert.equal(row.liveHealth.afterFrames.maxHp,row.liveHealth.entry.maxHp,'generic calibration cannot inflate live hidden health');assert.equal(row.liveHealth.afterFrames.maxHp,row.liveHealth.afterFrames.modelMax,'live HUD and hidden model share the same max HP');assert(row.liveHealth.afterFrames.maxHp<=3000000);
 row.liveHealth.wounded=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__,H=window.__HAPIL_INNER_FINAL_RC133__;window.__HAPIL_RAID_RC24__.tick(s);const a=H.boss(s);a.hp=Math.round(a.maxHp*.6);a.invulnerableUntil=s.time+10;return{time:s.time,hp:a.hp,maxHp:a.maxHp};});await page.waitForTimeout(400);row.liveHealth.afterWound=await liveHealth();assert(row.liveHealth.afterWound.hp<=row.liveHealth.wounded.hp+row.liveHealth.wounded.maxHp*.00038*(row.liveHealth.afterWound.time-row.liveHealth.wounded.time)+1e-6,'live calibration adds no HP beyond the preserved RC25 regeneration');
 row.liveHealth.restored=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__,N=window.__HAPIL_RC133_NATIVE__,B=window.__HAPIL_RC86_BRIDGE__,Q=window.__RC133_QA__,H=window.__HAPIL_INNER_FINAL_RC133__;window.__HAPIL_RAID_RC24__.tick(s);const before=H.boss(s).hp,raw=N.normalize(N.save(s,s.activeHeroId,[],{},0));s.enemies=Q.restoreEnemies(raw);B.restoreEntry(s,raw);const a=H.boss(s);return{time:s.time,before,hp:a?.hp,maxHp:a?.maxHp,modelMax:s.innerFinalRC133?.maxHp};});assert(row.liveHealth.restored.hp<=row.liveHealth.restored.before,'native save restoration cannot heal wounded hidden HP');await page.waitForTimeout(400);row.liveHealth.afterRestoreFrames=await liveHealth();assert.equal(row.liveHealth.afterRestoreFrames.maxHp,row.liveHealth.wounded.maxHp,'restored hidden actor stays bounded across live frames');assert(row.liveHealth.afterRestoreFrames.hp<=row.liveHealth.restored.hp+row.liveHealth.restored.maxHp*.00038*(row.liveHealth.afterRestoreFrames.time-row.liveHealth.restored.time)+1e-6,'restored live frames add only the preserved RC25 regeneration');assert.equal(row.liveHealth.afterRestoreFrames.maxHp,row.liveHealth.afterRestoreFrames.modelMax);
 row.liveBossFirst=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__,H=window.__HAPIL_INNER_FINAL_RC133__,hp=s.hp;window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();const a=H.boss(s);return {reason:s.innerFinalRC133?.clash?.reason,used:s.innerFinalRC133?.clash?.used,bossHp:a?.hp,bossMax:a?.maxHp,hp:s.hp,beforeHp:hp,mood:H.mood(s)};});assert.equal(row.liveBossFirst.reason,'boss');assert.equal(row.liveBossFirst.used,true);assert.equal(row.liveBossFirst.bossHp,Math.ceil(row.liveBossFirst.bossMax*.22));assert.equal(row.liveBossFirst.hp,row.liveBossFirst.beforeHp);assert.equal(row.liveBossFirst.mood,'opposition');
 row.liveCompletion=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;window.__MONGSE_QA_API__.forceDefeatCurrentBossR4();return {phase:s.innerFinalRC133?.phase,bossDefeated:s.bossDefeated,liveInner:!!window.__HAPIL_INNER_FINAL_RC133__.boss(s),cleared:window.__HAPIL_RC86_BRIDGE__.zoneCombatCleared(s,s.zone),mood:window.__HAPIL_INNER_FINAL_RC133__.mood(s)};});assert.deepEqual(row.liveCompletion,{phase:'complete',bossDefeated:true,liveInner:false,cleared:true,mood:'normal'});
 row.renderStates=[];
 await page.evaluate(()=>{const proto=CanvasRenderingContext2D.prototype,base=proto.drawImage;window.__RC133_MEDIA_DRAW__=base;proto.drawImage=function(...args){const src=args[0]?.src;if(window.__RC133_MEDIA_PROBE__&&src?.includes('/rc133/art/')){window.__RC133_MEDIA_PROBE__.paths.add(new URL(src).pathname);if(/\/(?:base|awake)-[0-7]\.png/.test(src))window.__RC133_MEDIA_PROBE__.bodyFilters.push(this.filter);}return base.apply(this,args);};});
 for(const mode of ['normal','player','boss','opposition']){await page.evaluate(mode=>{const s=window.__RC133_FIXTURES__.hidden;s.hp=240;s.innerFinalRC133.phase='fight';s.innerFinalRC133.awake=['boss','opposition'].includes(mode)?7:0;s.samongPassiveRC91={active:['player','opposition'].includes(mode)?7:0,cooldown:77,duration:7,heroId:'gunner'};s.innerFinalRC133.intro=0;s.innerFinalRC133.awakeningCooldown=14;s.timeStopUntil=0;window.__HAPIL_INNER_FINAL_RC133__.tick(s,.016);window.__RC133_FIXED_STATE__=s;window.__RC133_MEDIA_PROBE__={paths:new Set(),bodyFilters:[],compositions:window.__HAPIL_INNER_FINAL_RC133__.metrics().frames};},mode);await page.waitForTimeout(200);
  const rendered=await page.evaluate(()=>{const H=window.__HAPIL_INNER_FINAL_RC133__,s=window.__RC133_FIXED_STATE__,p=window.__RC133_MEDIA_PROBE__;return {mood:H.mood(s),sprite:H.boss(s)?.sprite,paths:[...p.paths],bodyFilters:[...new Set(p.bodyFilters)],compositions:H.metrics().frames-p.compositions};});row.renderStates.push(rendered);assert.equal(rendered.mood,mode);assert(rendered.bodyFilters.length>0&&rendered.bodyFilters.every(f=>['brightness(1.8) contrast(0.8)','brightness(2.2) contrast(0.85)'].includes(f)),'native hidden body brightness is isolated before whole-frame mood composition');assert(rendered.paths.some(p=>p.includes(['boss','opposition'].includes(mode)?'/awake-':'/base-')),'actual uploaded body frame must reach native drawImage');assert(rendered.paths.includes('/assets/rc133/art/arena.webp'));if(mode!=='normal')assert(rendered.compositions>0,'full native frame applies the requested persona compositor');await page.screenshot({path:path.join(out,name+'-inner-'+mode+'.png')});}
 await page.evaluate(()=>{CanvasRenderingContext2D.prototype.drawImage=window.__RC133_MEDIA_DRAW__;delete window.__RC133_MEDIA_PROBE__;});
 // Actual full-frame path must not fall back to ordinary awakening grayscale
 // after the persona fight ends while the player's buff remains active.
 await page.evaluate(()=>{const s=window.__RC133_FIXTURES__.hidden;s.innerFinalRC133.phase='complete';s.innerFinalRC133.awake=0;s.samongPassiveRC91.active=7;window.__RC133_END_FILTER__={start:window.__RC133_FRAMES__??0,grayscale:0};const proto=CanvasRenderingContext2D.prototype,base=proto.drawImage;window.__RC133_END_DRAW__=base;proto.drawImage=function(...args){if(args[0]===this.canvas&&this.filter.includes('grayscale'))window.__RC133_END_FILTER__.grayscale++;return base.apply(this,args);};});await page.waitForTimeout(200);row.endFilter=await page.evaluate(()=>{const row=window.__RC133_END_FILTER__;CanvasRenderingContext2D.prototype.drawImage=window.__RC133_END_DRAW__;return {frames:window.__RC133_FRAMES__-row.start,grayscalePasses:row.grayscale};});assert(row.endFilter.frames>0);assert.equal(row.endFilter.grayscalePasses,0);
 await page.evaluate(()=>{delete window.__RC133_FIXED_STATE__;});assert.deepEqual(row.errors,[]);assert.deepEqual(row.missing,[]);row.status='passed';
 }catch(e){row.status='failed';row.error=String(e.stack||e);}finally{save();console.log('RC133_BROWSER_PROFILE',JSON.stringify({name,status:row.status,error:row.error,native:{checks:row.native?.checks,problems:row.native?.problems},liveHidden:row.liveHidden,liveHealth:row.liveHealth,errors:row.errors,missing:row.missing}));await context.close();}
}
 report.status=report.profiles.every(r=>r.status==='passed')?'passed':'failed';
}finally{save();await browser?.close();server.close();process.exitCode=report.status==='passed'?0:1;}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
