'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results','rc130'));
const suites=['rc130-unit','rc130-browser','rc129-unit','rc129-browser','rc129-startup','rc127-policy','rc127-browser','rc43-bloodied-projectile-flight','rc126-finite-native','rc126-combat-browser','rc115-map-advance-smoke','rc115-natural-story-portal-browser','rc116-laser-continuity-browser','rc116-laser-telegraph-browser','rc119-laser-body-browser','story-narration-mixing','story-narration-media-races','story-narration-webaudio-races','story-narration-original-timing','story-narration-manifest','story-narration-audio-browser'];
fs.mkdirSync(out,{recursive:true});const report={version:'RC130',startingMain:'41d9d75ffffd9b4a2d8f51c90a8a08946f021864',testedCommit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),startedAt:new Date().toISOString(),status:'running',suites:[],runtimeHashes:{},attachment:{name:'오디오2.zip',imported:false,reason:'local execution service unavailable; uploaded archive not read or modified'},scope:'Unit/staged renderer coverage is separate from natural startup and one native Story first-boss/portal run.'};
const save=()=>fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));save();
for(const file of ['index.html','assets/index-v31526.js','assets/rc130/projectile-policy.js','assets/rc130/audio-policy.js','assets/rc23/feedback.js','assets/rc128/combat-feedback.js','assets/rc77/connected-laser.js','assets/rc127/combat-policy.js','assets/rc127/dark-jelly.js','assets/rc129/danmaku-director.js','assets/rc129/danmaku-hud.js','assets/story-narration/v1/mixer.js','assets/story-narration/v1/player.js']){
 if(fs.existsSync(path.join(root,file)))report.runtimeHashes[file]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
}
for(const name of suites){const folder=path.join(out,name);fs.mkdirSync(folder,{recursive:true});const start=Date.now();const r=cp.spawnSync(process.execPath,['tests/'+name+'.cjs'],{cwd:root,encoding:'utf8',maxBuffer:32*1024*1024,timeout:240000,env:{...process.env,HAPIL_QA_OUTPUT:folder,HAPIL_RELEASE_OUTPUT:folder}});fs.writeFileSync(path.join(folder,'stdout.log'),r.stdout||'');fs.writeFileSync(path.join(folder,'stderr.log'),r.stderr||'');const row={name,status:r.status===0&&!r.error?'passed':'failed',exitCode:r.status,durationMs:Date.now()-start,error:r.error?String(r.error):null};report.suites.push(row);save();console.log('RC130_SUITE',JSON.stringify(row));if(name.startsWith('rc130')||row.status==='failed'){console.log((r.stdout||'').slice(-16000));console.error((r.stderr||'').slice(-10000));}}
report.status=report.suites.every(r=>r.status==='passed')?'passed':'failed';report.finishedAt=new Date().toISOString();report.passed=report.suites.filter(r=>r.status==='passed').length;report.failed=report.suites.length-report.passed;save();console.log('RC130_RESULT',JSON.stringify(report));process.exitCode=report.failed?1:0;
