'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'..'),out=process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results/rc132');fs.mkdirSync(out,{recursive:true});const mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.webp':'image/webp','.png':'image/png','.wav':'audio/wav','.mp3':'audio/mpeg','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{let file;try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));}catch{res.writeHead(400).end();return;}if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={status:'running',commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),scope:'Native UI startup and staged post-defeat transitions. QA stages the checkpoint and invokes the native death handler; not natural boss kills or full campaigns.',profiles:[],userSaveReproduced:false};const save=()=>fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));
try{browser=await chromium.launch({executablePath:process.env.HAPIL_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});
for(const[name,width,height,mobile]of[['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){
 const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1}),page=await context.newPage(),row={name,status:'running',errors:[],httpErrors:[],samples:[]};report.profiles.push(row);page.setDefaultTimeout(30000);page.on('pageerror',e=>row.errors.push(String(e.stack||e)));page.on('response',r=>{if(r.status()>=400)row.httpErrors.push({url:r.url(),status:r.status()});});
 try{
  await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_SAMONG_RC91__?.installed&&window.__HAPIL_MIRROR_V31347__?.removed);await page.keyboard.press('Escape');await page.evaluate(()=>window.__HAPIL_SAMONG_RC91__.unlock(null,'777'));await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();assert.equal(await page.locator('[data-game-mode-v31354="HELL"]:visible').count(),0);await page.locator('[data-game-mode-v31354="DREAM"]').click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__);for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
  const t=await page.evaluate(()=>window.__MONGSE_QA_STATE__.time);await page.waitForTimeout(1500);assert(await page.evaluate(()=>window.__MONGSE_QA_STATE__.time)>t,'unmodified initial combat advances');
  row.stage=await page.evaluate(()=>{window.__MONGSE_QA_API__.setHero('hunter');const result=window.__MONGSE_QA_API__.stageV3128BossShowcase('ep1b07');window.__HAPIL_CONTROLS_V31329__.setMode('full');return result;});await page.waitForTimeout(500);
  const sample=()=>page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__,B=window.__HAPIL_CONTROLS_V31329__.binding;return{zone:s.zone,time:s.time,hp:s.hp,hero:s.activeHeroId,x:s.x,y:s.y,bossDefeated:s.bossDefeated,waves:[...s.spawnedWaves],clues:[...s.clues],drops:s.egoDrops?.length,enemies:(s.enemies||[]).map(a=>({id:a.id,hp:a.hp,phase:a.currentPhase})),gate:window.__HAPIL_FLOW_V31343__.gate(s),plan:window.__HAPIL_AUTOPROGRESS_V31301__.plan(s,B.settings.current),speed:s.rc127MovementSpeed,mirror:window.__HAPIL_MIRROR_V31347__.metrics(),budget:window.__HAPIL_DREAM_BALANCE_RC132__.snapshot()};});
  row.samples.push(await sample());assert.equal(row.samples[0].gate.clear,false,'live wrath boss cannot be skipped');assert.equal(row.samples[0].hero,'hunter');
  row.legacyMirror=await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__,hp=s.hp,M=window.__HAPIL_MIRROR_V31347__;s.dreamMirrorLasersV31347=[{dreamMirrorLaserV31347:true,zone:s.zone,sourceId:'b07-boss',fireAt:s.time-1,endAt:s.time+5,damage:999}];M.tick(s,.016);return{remaining:s.dreamMirrorLasersV31347.length,hpUnchanged:s.hp===hp,newCast:M.spawn(s,{},{}),removed:M.removed};});assert.deepEqual(row.legacyMirror,{remaining:0,hpUnchanged:true,newCast:null,removed:true});
  row.defeat=await page.evaluate(()=>window.__MONGSE_QA_API__.forceDefeatCurrentBossR4());assert(row.defeat.pass,'native death handler removes boss');
  for(let i=0;i<40;i++){await page.waitForTimeout(500);const value=await sample();row.samples.push(value);save();if(value.zone!=='ep1b07')break;}
  const last=row.samples.at(-1);assert.equal(last.zone,'ep1b08','post-defeat native movement and portal must reach next zone');assert(last.hp>0,'transition is not a death/respawn');assert(last.clues.includes('ego-reward-v31217:ep1b07'),'native clear reward retained');assert(row.samples.every(v=>Math.abs(v.speed-6.471685)<1e-8),'777 basic speed retained');assert(row.samples.every(v=>v.mirror.created===0&&v.mirror.hits===0&&v.mirror.draws===0),'removed mirror cannot generate, hurt or draw');assert.deepEqual(row.errors,[]);assert.deepEqual(row.httpErrors,[]);row.status='passed';
 }catch(e){row.status='failed';row.error=String(e.stack||e);}finally{await page.screenshot({path:path.join(out,'wrath-'+name+'.png')}).catch(e=>{row.screenshotError=String(e);});save();console.log('RC132_BROWSER_PROFILE',JSON.stringify({name,status:row.status,error:row.error,last:row.samples.at(-1)}));await context.close();}
}
report.wrathConsistency=await require('./rc132-wrath-regression.cjs').run(browser,'http://127.0.0.1:'+server.address().port+'/',out);
report.status=report.profiles.length===3&&report.profiles.every(r=>r.status==='passed')&&report.wrathConsistency.status==='passed'?'passed':'failed';
}catch(e){report.status='failed';report.error=String(e.stack||e);}finally{save();await browser?.close();server.close();console.log('RC132_BROWSER_RESULT',JSON.stringify({status:report.status,profiles:report.profiles.map(r=>({name:r.name,status:r.status})),scope:report.scope,userSaveReproduced:false}));process.exitCode=report.status==='passed'?0:1;}})();
