'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results/rc131'));fs.mkdirSync(out,{recursive:true});
const git=(...args)=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();
const report={version:'RC131',startingMain:'a4d4a73e5b551dd7bae2ec896294cd93cdef8402',testedCommit:git('rev-parse','HEAD'),status:'running',suites:[],files:{},scope:'Unit/geometry/byte checks, staged native render/audio checks, and one natural STORY first-boss/portal progression are distinct. Not all-hero full campaigns or physical phone/speaker validation.'};
const save=()=>fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));
const suites=['rc131-preservation','rc131-unit','rc131-browser','rc130-unit','rc130-isolation','rc130-browser','rc129-unit','rc129-browser','rc127-policy','rc127-browser','combat-audio-assets','combat-audio-controller','combat-audio-bridge','combat-audio-native-sfx','combat-audio-browser','rc116-laser-continuity-browser','rc115-natural-story-portal-browser','story-narration-mixing','story-narration-media-races','story-narration-webaudio-races'];
for(const f of ['index.html','assets/index-v31526.js','assets/rc23/feedback.js','assets/rc128/combat-feedback.js','assets/combat-audio/v1/native-bridge.js','assets/rc131/audio-cues.js','assets/rc131/manifest.json','audio/rc131/attack-wood.ogg','audio/rc131/attack-melee.ogg','audio/rc131/hurt-neutral.ogg','audio/rc131/parry.ogg'])report.files[f]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');save();
for(const name of suites){const folder=path.join(out,name);fs.mkdirSync(folder,{recursive:true});const start=Date.now(),r=cp.spawnSync(process.execPath,['tests/'+name+'.cjs'],{cwd:root,encoding:'utf8',maxBuffer:48*1024*1024,timeout:300000,env:{...process.env,HAPIL_SOURCE_SHA:report.testedCommit,HAPIL_QA_OUTPUT:folder,HAPIL_RELEASE_OUTPUT:folder,HAPIL_COMBAT_AUDIO_OUTPUT:folder,HAPIL_NATURAL_LIMIT_MS:'180000'}});fs.writeFileSync(path.join(folder,'stdout.log'),r.stdout||'');fs.writeFileSync(path.join(folder,'stderr.log'),r.stderr||'');const row={name,status:r.status===0&&!r.error?'passed':'failed',exitCode:r.status,durationMs:Date.now()-start,error:r.error?String(r.error):null};
 if(name==='rc115-natural-story-portal-browser'&&row.status==='passed'){try{const x=JSON.parse(fs.readFileSync(path.join(folder,'natural-story-results.json'),'utf8'));if(x.usedProgressCheats!==false||x.changedZone!==true||!(x.final?.hp>0)||x.errors?.length||x.failedResponses?.length)throw Error('Natural first-boss/portal progress not proven');row.progress={first:x.first?.zone,last:x.final?.zone,hp:x.final?.hp,usedProgressCheats:x.usedProgressCheats};}catch(e){row.status='failed';row.error=String(e);}}
 report.suites.push(row);save();console.log('RC131_SUITE',JSON.stringify(row));if(row.status==='failed')console.log((r.stdout||'').slice(-2000),(r.stderr||'').slice(-6000));}
report.passed=report.suites.filter(r=>r.status==='passed').length;report.failed=report.suites.length-report.passed;report.status=report.failed?'failed':'passed';save();console.log('RC131_RESULT',JSON.stringify(report));process.exitCode=report.failed?1:0;
