'use strict';
// Read-only deployed-service check. No response interception or state fixtures.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'../..'),base=process.env.HAPIL_TEST_BASE||'https://kjb7876-lang.github.io/hapil1/',out=process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results/rc126-public');fs.mkdirSync(out,{recursive:true});
const files=['index.html','assets/index-v31526.js','assets/rc126/finite-native.js','assets/rc126/combat-safety.js','assets/rc108/laser-topology.js','assets/rc95/combat-flow.js','assets/combat-v31402/projectile-pipeline.js','assets/combat-v31402/contact-geometry.js','assets/rc43/bloodied-flight.js','assets/rc77/connected-laser.js','assets/rc124/laser-overrun.js','assets/rc125/adaptive-battlefield.js','assets/rc125/adaptive-battlefield.css'];
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function main(){const report={base,testedCommit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),files:[],screens:[],scope:'Read-only published startup, not full campaigns or physical phones'};let browser;
try{
 for(const file of files){const url=new URL(file,base);url.searchParams.set('rc126-verify',Date.now());const r=await fetch(url,{signal:AbortSignal.timeout(30000)}),body=Buffer.from(await r.arrayBuffer()),expected=hash(fs.readFileSync(path.join(root,file))),actual=hash(body);report.files.push({file,status:r.status,expected,actual});assert.equal(r.status,200,file);assert.equal(actual,expected,'Published bytes differ: '+file);}
 browser=await chromium.launch({chromiumSandbox: true, executablePath:process.env.HAPIL_CHROMIUM,args:['--disable-dev-shm-usage']});
 for(const [name,width,height,mobile]of [['pc',1180,757,false],['portrait',390,844,true],['landscape',844,390,true]]){const ctx=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1}),page=await ctx.newPage(),row={name,errors:[],httpErrors:[],requestFailures:[],samples:[]};report.screens.push(row);page.setDefaultTimeout(30000);page.on('pageerror',e=>row.errors.push(e.stack||e.message));page.on('requestfailed',r=>row.requestFailures.push({url:r.url(),resourceType:r.resourceType(),failure:r.failure()}));page.on('response',r=>{if(r.status()>=400)row.httpErrors.push({url:r.url(),status:r.status()});});
 const url=new URL(base);url.searchParams.set('rc126-page',report.testedCommit+'-'+Date.now());url.searchParams.set('qa','1');const documentResponse=await page.goto(url.href);assert(documentResponse,'The browser navigation returned no HTML response');const documentHash=hash(Buffer.from(await documentResponse.body())),expectedDocumentHash=report.files.find(file=>file.file==='index.html')?.actual;row.document={url:url.href,status:documentResponse.status(),expected:expectedDocumentHash,actual:documentHash};assert.equal(row.document.status,200,'The navigation document must be served successfully');assert.equal(documentHash,expectedDocumentHash,'The browser must execute the exact committed HTML bytes');
 const readinessSnapshot=()=>page.evaluate(()=>({readyState:document.readyState,url:location.href,storyRecords:window.__HAPIL_STORY_DATA_RC51__?.records?.length??null,policyVersion:window.__HAPIL_POLICY_V31400__?.version??null,finiteVersion:window.__HAPIL_FINITE_NATIVE_RC126__?.version??null,safetyInstalled:window.__HAPIL_COMBAT_SAFETY_RC126__?.snapshot().installed??false,zone:window.__MONGSE_QA_STATE__?.zone??null,phase:window.__HAPIL_CONTROLS_V31329__?.binding?.phase??null,openingPhase:window.__MONGSE_CHRISTIAN_OPENING_V31236__?.phase??null,visibleButtons:[...document.querySelectorAll('button')].filter(b=>!b.hidden&&b.getClientRects().length).map(b=>b.innerText.trim()).filter(Boolean).slice(0,20)}));
 await page.waitForFunction(()=>window.__HAPIL_COMBAT_SAFETY_RC126__?.snapshot().installed&&window.__HAPIL_FINITE_NATIVE_RC126__?.version==='RC126-finite-2').catch(async error=>{row.readinessFailure={stage:'runtime-install',error:String(error),observed:await readinessSnapshot()};console.log('RC126_READINESS_FAILURE',JSON.stringify(row));throw error;});await page.keyboard.press('Escape');await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__?.zone==='dist00').catch(async error=>{row.readinessFailure={stage:'dist00-entry',error:String(error),observed:await readinessSnapshot()};console.log('RC126_READINESS_FAILURE',JSON.stringify(row));throw error;});await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.setMode('full'));for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
 for(let i=0;i<12;i++){await page.waitForTimeout(2000);row.samples.push(await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;return{zone:s.zone,time:s.time,hp:s.hp,hero:s.activeHeroId,shots:s.hostileProjectiles.length,finite:s.hostileProjectiles.every(q=>[q.x,q.y,q.vx,q.vy].every(Number.isFinite)),finiteNative:window.__HAPIL_FINITE_NATIVE_RC126__.version,rc126:window.__HAPIL_COMBAT_SAFETY_RC126__.snapshot(s),adaptive:window.__HAPIL_ADAPTIVE_RC125__.snapshot().installed,deathDialog:!!document.querySelector('#hapil-death-verse-rc59')};}));}
 row.final=row.samples.at(-1);await page.screenshot({path:path.join(out,'published-'+name+'.png')});assert.deepEqual(row.errors,[]);assert.deepEqual(row.httpErrors,[]);assert(row.final.time>5&&row.final.rc126.installed&&row.final.adaptive&&row.samples.every(r=>r.finite));row.passed=true;console.log('RC126_PUBLIC',JSON.stringify(row));fs.writeFileSync(path.join(out,'published-results.json'),JSON.stringify(report,null,2));await ctx.close();
 }
 report.passed=true;console.log('RC126_PUBLIC_SUMMARY',JSON.stringify({testedCommit:report.testedCommit,files:report.files.length,screens:report.screens.map(s=>({name:s.name,passed:s.passed,final:s.final})),passed:true}));
}finally{fs.writeFileSync(path.join(out,'published-results.json'),JSON.stringify(report,null,2));await browser?.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
