'use strict';
// Linux Playwright WebKit compatibility, NOT physical iPhone or Apple Safari certification.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {webkit}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'../..'),out=process.env.HAPIL_QA_OUTPUT||path.join(root,'qa-results/rc126-webkit');fs.mkdirSync(out,{recursive:true});
const types={'.js':'text/javascript','.html':'text/html','.css':'text/css','.webp':'image/webp','.png':'image/png','.wav':'audio/wav','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html')));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',types[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={scope:'Unmodified Linux WebKit, synthetic touch input; not a physical phone, not all campaigns',sha:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),rows:[]};
try{browser=await webkit.launch();for(const [name,width,height,mobile]of[['pc-webkit',1180,757,false],['portrait-webkit',390,844,true],['landscape-webkit',844,390,true]]){const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:mobile?2:1,isMobile:mobile,hasTouch:mobile}),page=await ctx.newPage(),row={name,errors:[],httpErrors:[],samples:[]};report.rows.push(row);page.setDefaultTimeout(30000);page.on('pageerror',e=>row.errors.push(e.stack||e.message));page.on('response',r=>{if(r.status()>=400)row.httpErrors.push({url:r.url(),status:r.status()});});
try{await page.goto('http://127.0.0.1:'+server.address().port+'/?qa=1');await page.waitForFunction(()=>window.__HAPIL_COMBAT_SAFETY_RC126__?.snapshot().installed);await page.keyboard.press('Escape');await page.getByRole('button',{name:'새 게임 시작',exact:true}).click();await page.getByRole('button',{name:'이 편성으로 접속',exact:true}).click();await page.waitForFunction(()=>window.__MONGSE_QA_STATE__?.zone==='dist00');await page.evaluate(()=>window.__HAPIL_CONTROLS_V31329__.setMode('full'));
for(let i=0;i<12&&await page.locator('#hapil-story-rc51').count();i++){await page.keyboard.press('Enter');await page.waitForTimeout(100);}
await page.evaluate(()=>{window.__RC126_WEBKIT__={frames:0,touch:0,pointer:0};const f=()=>{window.__RC126_WEBKIT__.frames++;requestAnimationFrame(f);};requestAnimationFrame(f);const c=document.querySelector('.game-stage canvas');c.addEventListener('touchstart',()=>window.__RC126_WEBKIT__.touch++,{passive:true});c.addEventListener('pointerdown',()=>window.__RC126_WEBKIT__.pointer++,{passive:true});});
if(mobile){const c=page.locator('.game-stage canvas'),b=await c.boundingBox();await c.tap({position:{x:b.width*.62,y:b.height*.78}});}
for(let i=0;i<15;i++){await page.waitForTimeout(2000);row.samples.push(await page.evaluate(()=>{const s=window.__MONGSE_QA_STATE__;return{zone:s.zone,time:s.time,hp:s.hp,mode:s.gameModeV31346,shots:s.hostileProjectiles.length,deadDialog:!!document.querySelector('#hapil-death-verse-rc59'),metrics:window.__RC126_WEBKIT__,rc126:window.__HAPIL_COMBAT_SAFETY_RC126__.snapshot().stats};}));if(row.errors.length)break;}
row.final=row.samples.at(-1);row.passed=row.errors.length===0&&row.httpErrors.length===0&&row.final?.time>5&&row.final.metrics.frames>30&&(!mobile||row.final.metrics.touch>0);await page.screenshot({path:path.join(out,name+'.png')});
}catch(e){row.passed=false;row.failure=String(e.stack||e);try{await page.screenshot({path:path.join(out,name+'-failure.png')});}catch{}}
console.log('RC126_WEBKIT',JSON.stringify(row));fs.writeFileSync(path.join(out,'webkit-results.json'),JSON.stringify(report,null,2));await ctx.close();}
assert(report.rows.every(r=>r.passed),'WebKit compatibility observations failed');
}finally{fs.writeFileSync(path.join(out,'webkit-results.json'),JSON.stringify(report,null,2));await browser?.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
