'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert/strict'),crypto=require('crypto'),acorn=require(process.env.RC132_MODULES+'/acorn');
const BASE='a624e894788a8a1c21d6ca611299985d62eaf97e',root=path.resolve(__dirname,'..');
const git=(...a)=>cp.execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:40*1024*1024});try{git('cat-file','-e',BASE+':index.html');}catch{git('fetch','--no-tags','--depth=1','origin',BASE);}
const sha=s=>crypto.createHash('sha256').update(s).digest('hex'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),old=f=>git('show',BASE+':'+f),rows=[];
function findFunction(s,test){const functions=[];function walk(n){if(!n||typeof n!=='object')return;if(/Function/.test(n.type)&&n.body&&test(s.slice(n.start,n.end)))functions.push(n);for(const[k,v]of Object.entries(n)){if(k==='start'||k==='end')continue;if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v.type==='string')walk(v);}}walk(acorn.parse(s,{ecmaVersion:'latest',sourceType:'module'}));functions.sort((a,b)=>(a.end-a.start)-(b.end-b.start));assert(functions[0]);return s.slice(functions[0].start,functions[0].end);}
function add(file,ops){const before=old(file),after=read(file);let text=before;for(const op of ops){assert.equal(text.split(op.from).length-1,1,'unique '+file+' '+op.name);text=text.replace(op.from,op.to);}assert.equal(text,after,'exact authorized reconstruction '+file);rows.push({file,beforeSha256:sha(before),afterSha256:sha(after),operations:ops});}
const b=old('assets/index-v31526.js'),s=read('assets/index-v31526.js');
add('assets/index-v31526.js',[
 {name:'remove only DREAM mirror attack closure; preserve original memory artwork functions',from:findFunction(b,t=>t.length<100000&&t.includes('window.__HAPIL_MIRROR_V31347__')&&t.includes('function spawn(')),to:findFunction(s,t=>t.includes('RC132_MIRROR_REMOVED'))},
 {name:'bound actual party lifesteal',from:'a.hp=Math.min(a.maxHp,a.hp+dealt*.08*scale);',to:'/* RC132_PARTY_SUSTAIN */const healing=window.__HAPIL_DREAM_BALANCE_RC132__?.lifesteal(s,a,dealt*.08*scale)??dealt*.08*scale;a.hp=Math.min(a.maxHp,a.hp+healing);'}
]);
add('assets/combat-v31412/outgoing-native.js',[{name:'bound actual main-hero lifesteal',from:'          ((a.hp += e),core.outgoingHeal(a,o,e),',to:'          // RC132_NATIVE_SUSTAIN: bound earned lifesteal before committing the HP change.\n          e = window.__HAPIL_DREAM_BALANCE_RC132__?.lifesteal(a,a,e) ?? e;\n          ((a.hp += e),core.outgoingHeal(a,o,e),'}]);
const beforeHTML=old('index.html'),afterHTML=read('index.html');const fromTag='<script src="./assets/rc130/projectile-policy.js';let expected=beforeHTML.replace(fromTag,'<script src="./assets/rc132/dream-balance.js?v=43201"></script>\n    '+fromTag);expected=expected.replace(/(assets\/combat-v31412\/outgoing-native\.js\?v=)[^"']+/g,(_,p)=>p+'43201').replace(/(assets\/index-v31526\.js\?v=)[^"']+/g,(_,p)=>p+'43201');assert.equal(afterHTML,expected,'only declared loaders and cache keys');add('index.html',[{name:'add one loader and update two changed runtime cache keys',from:beforeHTML,to:afterHTML}]);
const result={version:1,base:BASE,rows,newRuntimeFiles:['assets/rc132/dream-balance.js'],scope:'exact tested transformations, no unlisted runtime edits'};
fs.writeFileSync(path.join(root,'tools/rc132-runtime-delta.json'),JSON.stringify(result,null,2)+'\n');console.log('RC132_DELTA_EXPORTED',JSON.stringify({base:BASE,files:rows.map(r=>({file:r.file,before:r.beforeSha256,after:r.afterSha256}))}));
